export const data = {
  "display": "",
  "components": [
    {
      "label": "Art Commencement",
      "tag": "p",
      "className": "",
      "attrs": [
        {
          "attr": "",
          "value": ""
        }
      ],
      "content": "<span style=\"color:#B87108\">ART COMMENCEMENT</span>\n<hr>",
      "refreshOnChange": false,
      "customClass": "",
      "hidden": false,
      "tableView": false,
      "modalEdit": false,
      "key": "art_commencement",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "htmlelement",
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": true,
      "refreshOn": "",
      "redrawOn": "",
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "hideLabel": false,
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false,
        "unique": false,
        "multiple": false
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "id": "epkwh1"
    },
    {
      "label": "Columns",
      "columns": [
        {
          "components": [
            {
              "label": "ART Start Date ",
              "labelPosition": "top",
              "displayInTimezone": "viewer",
              "useLocaleSettings": true,
              "allowInput": false,
              "format": "yyyy-MM-dd",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "autofocus": false,
              "disabled": false,
              "tableView": false,
              "modalEdit": false,
              "enableDate": true,
              "datePicker": {
                "minDate": null,
                "maxDate": null,
                "disable": "",
                "disableFunction": "",
                "disableWeekends": false,
                "disableWeekdays": false,
                "showWeeks": true,
                "startingDay": 0,
                "initDate": "",
                "minMode": "day",
                "maxMode": "year",
                "yearRows": 4,
                "yearColumns": 5
              },
              "enableTime": true,
              "timePicker": {
                "showMeridian": true,
                "hourStep": 1,
                "minuteStep": 1,
                "readonlyInput": false,
                "mousewheel": true,
                "arrowkeys": true
              },
              "multiple": false,
              "defaultValue": "",
              "defaultDate": "new Date();",
              "customOptions": {},
              "persistent": true,
              "protected": false,
              "dbIndex": false,
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validate": {
                "required": true,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "strictDateValidation": false,
                "unique": false,
                "multiple": false
              },
              "unique": false,
              "validateOn": "change",
              "errorLabel": "",
              "key": "date_enrollment",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "datetime",
              "input": true,
              "prefix": "",
              "suffix": "<i ref=\"icon\" class=\"fa fa-calendar\" style=\"\"></i>",
              "refreshOn": "",
              "widget": {
                "type": "calendar",
                "displayInTimezone": "viewer",
                "language": "en",
                "useLocaleSettings": true,
                "allowInput": false,
                "mode": "single",
                "enableTime": true,
                "noCalendar": false,
                "format": "yyyy-MM-dd",
                "hourIncrement": 1,
                "minuteIncrement": 1,
                "time_24hr": false,
                "minDate": null,
                "disabledDates": "",
                "disableWeekends": false,
                "disableWeekdays": false,
                "disableFunction": "",
                "maxDate": null
              },
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "timezone": "",
              "datepickerMode": "day",
              "id": "esofof3s",
              "hideOnChildrenHidden": false
            }
          ],
          "offset": 0,
          "push": 0,
          "pull": 0,
          "width": 4
        },
        {
          "components": [
            {
              "label": "CD4 at start of ART",
              "labelPosition": "top",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "inputMask": "",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "persistent": true,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "case": "",
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": false,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "unique": false,
                "multiple": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "cd4",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "textfield",
              "input": true,
              "refreshOn": "",
              "inputType": "text",
              "id": "end3bgt",
              "defaultValue": "",
              "hideOnChildrenHidden": false
            }
          ],
          "offset": 0,
          "push": 0,
          "pull": 0,
          "width": 4
        },
        {
          "components": [
            {
              "label": "CD4%",
              "labelPosition": "top",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "inputMask": "",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "persistent": true,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "case": "",
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": false,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "unique": false,
                "multiple": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "cd4p",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "textfield",
              "input": true,
              "refreshOn": "",
              "inputType": "text",
              "id": "exmv3li",
              "defaultValue": "",
              "hideOnChildrenHidden": false
            }
          ],
          "offset": 0,
          "push": 0,
          "pull": 0,
          "width": 4
        }
      ],
      "autoAdjust": false,
      "hideOnChildrenHidden": false,
      "customClass": "",
      "hidden": false,
      "hideLabel": false,
      "tableView": false,
      "modalEdit": false,
      "key": "columns",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "columns",
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": false,
      "refreshOn": "",
      "redrawOn": "",
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "tree": false,
      "id": "eiu3g2",
      "path": "columns"
    },
    {
      "label": "Columns",
      "columns": [
        {
          "components": [
            {
              "label": "Original Regimen Line",
              "labelPosition": "top",
              "widget": "choicesjs",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "autofocus": false,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "dataSrc": "url",
              "data": {
                "resource": "",
                "json": "",
                "url": " http://lamisplus.org/base-module/api/regimen-lines",
                "custom": "",
                "headers": [
                  {
                    "key": "",
                    "value": ""
                  }
                ],
                "values": []
              },
              "valueProperty": "",
              "dataType": "",
              "template": "<span>{{ item.name }}</span>",
              "searchEnabled": true,
              "selectThreshold": 0.3,
              "readOnlyValue": false,
              "customOptions": {},
              "persistent": true,
              "protected": false,
              "dbIndex": false,
              "encrypted": false,
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": true,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "strictDateValidation": false,
                "unique": false,
                "multiple": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "regimen_line",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "select",
              "indexeddb": {
                "filter": {}
              },
              "minSearch": 0,
              "limit": 100,
              "input": true,
              "prefix": "",
              "suffix": "",
              "refreshOn": "",
              "redrawOn": "",
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "clearOnRefresh": false,
              "lazyLoad": true,
              "filter": "",
              "searchField": "",
              "authenticate": false,
              "selectFields": "",
              "searchThreshold": 0.3,
              "fuseOptions": {
                "include": "score",
                "threshold": 0.3
              },
              "id": "ehki9ft",
              "defaultValue": "",
              "selectValues": "",
              "disableLimit": false,
              "sort": "",
              "hideOnChildrenHidden": false
            }
          ],
          "offset": 0,
          "push": 0,
          "pull": 0,
          "width": 4
        },
        {
          "components": [
            {
              "label": "Original Regimen",
              "labelPosition": "top",
              "widget": "choicesjs",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "autofocus": false,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "dataSrc": "url",
              "data": {
                "values": [
                  {}
                ],
                "resource": "",
                "headers": [
                  {
                    "key": "",
                    "value": ""
                  }
                ],
                "json": "",
                "url": " http://lamisplus.org/base-module/api/regimens",
                "custom": ""
              },
              "valueProperty": "",
              "dataType": "",
              "template": "<span>{{ item.name }}</span>",
              "searchEnabled": true,
              "selectThreshold": 0.3,
              "readOnlyValue": false,
              "customOptions": {},
              "persistent": true,
              "protected": false,
              "dbIndex": false,
              "encrypted": false,
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": true,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "unique": false,
                "multiple": false,
                "strictDateValidation": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "regimen",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "select",
              "indexeddb": {
                "filter": {}
              },
              "minSearch": 0,
              "limit": 100,
              "input": true,
              "disableLimit": false,
              "hideOnChildrenHidden": false,
              "prefix": "",
              "suffix": "",
              "refreshOn": "",
              "redrawOn": "",
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "clearOnRefresh": false,
              "lazyLoad": true,
              "filter": "",
              "searchField": "",
              "authenticate": false,
              "selectFields": "",
              "searchThreshold": 0.3,
              "fuseOptions": {
                "include": "score",
                "threshold": 0.3
              },
              "id": "e3ysutf",
              "defaultValue": {},
              "selectValues": "",
              "sort": ""
            }
          ],
          "offset": 0,
          "push": 0,
          "pull": 0,
          "width": 4
        },
        {
          "components": [
            {
              "label": "Viral Load at Start of ART",
              "labelPosition": "top",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "inputMask": "",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "persistent": true,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "case": "",
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": false,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "unique": false,
                "multiple": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "viral_load",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "textfield",
              "input": true,
              "refreshOn": "",
              "inputType": "text",
              "id": "eqr72lb",
              "defaultValue": "",
              "hideOnChildrenHidden": false
            }
          ],
          "offset": 0,
          "push": 0,
          "pull": 0,
          "width": 4
        }
      ],
      "autoAdjust": false,
      "hideOnChildrenHidden": false,
      "customClass": "",
      "hidden": false,
      "hideLabel": false,
      "tableView": false,
      "modalEdit": false,
      "key": "columns1",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "columns",
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": false,
      "refreshOn": "",
      "redrawOn": "",
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "tree": false,
      "id": "e8ka0fe",
      "path": "columns1"
    },
    {
      "label": "Columns",
      "columns": [
        {
          "components": [
            {
              "label": "Functional Stage",
              "labelPosition": "top",
              "widget": "choicesjs",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "autofocus": false,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "dataSrc": "url",
              "data": {
                "resource": "",
                "json": "",
                "url": "http://lamisplus.org/base-module/api/application-codesets/codesetGroup?codesetGroup=FUNCTIONAL%20STATUS",
                "custom": "",
                "headers": [
                  {
                    "key": "",
                    "value": ""
                  }
                ],
                "values": []
              },
              "valueProperty": "",
              "dataType": "",
              "template": "<span>{{ item.display }}</span>",
              "searchEnabled": true,
              "selectThreshold": 0.3,
              "readOnlyValue": false,
              "customOptions": {},
              "persistent": true,
              "protected": false,
              "dbIndex": false,
              "encrypted": false,
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": false,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "strictDateValidation": false,
                "unique": false,
                "multiple": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "functional_status",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "select",
              "indexeddb": {
                "filter": {}
              },
              "minSearch": 0,
              "limit": 100,
              "input": true,
              "prefix": "",
              "suffix": "",
              "refreshOn": "",
              "redrawOn": "",
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "clearOnRefresh": false,
              "lazyLoad": true,
              "filter": "",
              "searchField": "",
              "authenticate": false,
              "selectFields": "",
              "searchThreshold": 0.3,
              "fuseOptions": {
                "include": "score",
                "threshold": 0.3
              },
              "id": "ef8i0r",
              "defaultValue": "",
              "selectValues": "",
              "disableLimit": false,
              "sort": "",
              "hideOnChildrenHidden": false
            }
          ],
          "offset": 0,
          "push": 0,
          "pull": 0,
          "width": 4
        },
        {
          "components": [
            {
              "label": "TB Status",
              "labelPosition": "top",
              "widget": "choicesjs",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "autofocus": false,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "dataSrc": "url",
              "data": {
                "resource": "",
                "json": "",
                "url": " http://lamisplus.org/base-module/api/application-codesets/codesetGroup?codesetGroup=TB_STATUS",
                "custom": "",
                "headers": [
                  {
                    "key": "",
                    "value": ""
                  }
                ],
                "values": []
              },
              "valueProperty": "",
              "dataType": "",
              "template": "<span>{{ item.display }}</span>",
              "searchEnabled": true,
              "selectThreshold": 0.3,
              "readOnlyValue": false,
              "customOptions": {},
              "persistent": true,
              "protected": false,
              "dbIndex": false,
              "encrypted": false,
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": false,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "strictDateValidation": false,
                "unique": false,
                "multiple": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "tb_status",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "select",
              "indexeddb": {
                "filter": {}
              },
              "minSearch": 0,
              "limit": 100,
              "input": true,
              "prefix": "",
              "suffix": "",
              "refreshOn": "",
              "redrawOn": "",
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "clearOnRefresh": false,
              "lazyLoad": true,
              "filter": "",
              "searchField": "",
              "authenticate": false,
              "selectFields": "",
              "searchThreshold": 0.3,
              "fuseOptions": {
                "include": "score",
                "threshold": 0.3
              },
              "id": "egm6s5",
              "defaultValue": "",
              "selectValues": "",
              "disableLimit": false,
              "sort": "",
              "hideOnChildrenHidden": false
            }
          ],
          "offset": 0,
          "push": 0,
          "pull": 0,
          "width": 4
        },
        {
          "components": [
            {
              "label": "Pregnancy Status",
              "labelPosition": "top",
              "widget": "choicesjs",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "autofocus": false,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "dataSrc": "url",
              "data": {
                "values": [
                  {}
                ],
                "resource": "",
                "url": "http://lamisplus.org/base-module/api/application-codesets/codesetGroup?codesetGroup=PREGANACY_STATUS",
                "headers": [
                  {
                    "key": "",
                    "value": ""
                  }
                ],
                "json": "",
                "custom": ""
              },
              "valueProperty": "",
              "dataType": "",
              "template": "<span>{{ item.display }}</span>",
              "searchEnabled": true,
              "selectThreshold": 0.3,
              "readOnlyValue": false,
              "customOptions": {},
              "persistent": true,
              "protected": false,
              "dbIndex": false,
              "encrypted": false,
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": false,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "unique": false,
                "multiple": false,
                "strictDateValidation": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "pregnancy_status",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "select",
              "indexeddb": {
                "filter": {}
              },
              "minSearch": 0,
              "limit": 100,
              "input": true,
              "disableLimit": false,
              "hideOnChildrenHidden": false,
              "prefix": "",
              "suffix": "",
              "refreshOn": "",
              "redrawOn": "",
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "clearOnRefresh": false,
              "lazyLoad": true,
              "filter": "",
              "searchField": "",
              "authenticate": false,
              "selectFields": "",
              "searchThreshold": 0.3,
              "fuseOptions": {
                "include": "score",
                "threshold": 0.3
              },
              "id": "ew9s7qe",
              "defaultValue": {}
            }
          ],
          "offset": 0,
          "push": 0,
          "pull": 0,
          "width": 4
        }
      ],
      "autoAdjust": false,
      "hideOnChildrenHidden": false,
      "customClass": "",
      "hidden": false,
      "hideLabel": false,
      "tableView": false,
      "modalEdit": false,
      "key": "columns2",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "columns",
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": false,
      "refreshOn": "",
      "redrawOn": "",
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "tree": false,
      "id": "ex2wwvea",
      "path": "columns2"
    },
    {
      "label": "Columns",
      "columns": [
        {
          "components": [
            {
              "label": "Body Weight(kg)",
              "labelPosition": "top",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": false,
              "modalEdit": false,
              "multiple": false,
              "persistent": true,
              "delimiter": false,
              "requireDecimal": false,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": false,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "min": "",
                "max": "",
                "strictDateValidation": false,
                "step": "any",
                "integer": "",
                "unique": false,
                "multiple": false
              },
              "errorLabel": "",
              "key": "body_weight",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "number",
              "input": true,
              "unique": false,
              "refreshOn": "",
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "id": "eipppzs",
              "hideOnChildrenHidden": false,
              "defaultValue": null
            }
          ],
          "offset": 0,
          "push": 0,
          "pull": 0,
          "width": 4
        },
        {
          "components": [
            {
              "label": "Height(cm)",
              "labelPosition": "top",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": false,
              "modalEdit": false,
              "multiple": false,
              "persistent": true,
              "delimiter": false,
              "requireDecimal": false,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": false,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "min": "",
                "max": "",
                "strictDateValidation": false,
                "step": "any",
                "integer": "",
                "unique": false,
                "multiple": false
              },
              "errorLabel": "",
              "key": "height",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "number",
              "input": true,
              "unique": false,
              "refreshOn": "",
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "id": "efk01zo",
              "hideOnChildrenHidden": false,
              "defaultValue": null
            }
          ],
          "offset": 0,
          "push": 0,
          "pull": 0,
          "width": 4
        },
        {
          "components": [
            {
              "label": "Blood Pressure(mmHg)",
              "labelPosition": "top",
              "placeholder": "systolic",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": false,
              "modalEdit": false,
              "multiple": false,
              "persistent": true,
              "delimiter": false,
              "requireDecimal": false,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": false,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "min": "",
                "max": "",
                "unique": false,
                "multiple": false,
                "strictDateValidation": false,
                "step": "any",
                "integer": ""
              },
              "errorLabel": "",
              "key": "systolic",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "number",
              "input": true,
              "hideOnChildrenHidden": false,
              "unique": false,
              "refreshOn": "",
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "id": "e15ib58",
              "defaultValue": null
            }
          ],
          "offset": 0,
          "push": 0,
          "pull": 0,
          "width": 4
        }
      ],
      "autoAdjust": false,
      "hideOnChildrenHidden": false,
      "customClass": "",
      "hidden": false,
      "hideLabel": false,
      "tableView": false,
      "modalEdit": false,
      "key": "columns3",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "columns",
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": false,
      "refreshOn": "",
      "redrawOn": "",
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "tree": false,
      "id": "efm5gxvd",
      "path": "columns3"
    },
    {
      "label": "Columns",
      "columns": [
        {
          "components": [
            {
              "label": "Blood Pressure(mmHg)",
              "labelPosition": "top",
              "placeholder": "diastolic",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": false,
              "modalEdit": false,
              "multiple": false,
              "persistent": true,
              "delimiter": false,
              "requireDecimal": false,
              "inputFormat": "plain",
              "protected": false,
              "dbIndex": false,
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": false,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "min": "",
                "max": "",
                "strictDateValidation": false,
                "step": "any",
                "integer": "",
                "unique": false,
                "multiple": false
              },
              "errorLabel": "",
              "key": "diastolic",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "number",
              "input": true,
              "unique": false,
              "refreshOn": "",
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "id": "efisrm7",
              "hideOnChildrenHidden": false,
              "defaultValue": null
            }
          ],
          "offset": 0,
          "push": 0,
          "pull": 0,
          "width": 4
        },
        {
          "components": [
            {
              "label": "Date of Next Appointment",
              "labelPosition": "top",
              "displayInTimezone": "viewer",
              "useLocaleSettings": true,
              "allowInput": false,
              "format": "yyyy-MM-dd",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "autofocus": false,
              "disabled": false,
              "tableView": false,
              "modalEdit": false,
              "enableDate": true,
              "datePicker": {
                "minDate": null,
                "maxDate": null,
                "disable": "",
                "disableFunction": "",
                "disableWeekends": false,
                "disableWeekdays": false,
                "showWeeks": true,
                "startingDay": 0,
                "initDate": "",
                "minMode": "day",
                "maxMode": "year",
                "yearRows": 4,
                "yearColumns": 5
              },
              "enableTime": true,
              "timePicker": {
                "showMeridian": true,
                "hourStep": 1,
                "minuteStep": 1,
                "readonlyInput": false,
                "mousewheel": true,
                "arrowkeys": true
              },
              "multiple": false,
              "defaultValue": "",
              "defaultDate": "",
              "customOptions": {},
              "persistent": true,
              "protected": false,
              "dbIndex": false,
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validate": {
                "required": true,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "strictDateValidation": false,
                "unique": false,
                "multiple": false
              },
              "unique": false,
              "validateOn": "change",
              "errorLabel": "",
              "key": "next_appointment",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "datetime",
              "input": true,
              "prefix": "",
              "suffix": "<i ref=\"icon\" class=\"fa fa-calendar\" style=\"\"></i>",
              "refreshOn": "",
              "widget": {
                "type": "calendar",
                "displayInTimezone": "viewer",
                "language": "en",
                "useLocaleSettings": true,
                "allowInput": false,
                "mode": "single",
                "enableTime": true,
                "noCalendar": false,
                "format": "yyyy-MM-dd",
                "hourIncrement": 1,
                "minuteIncrement": 1,
                "time_24hr": false,
                "minDate": null,
                "disabledDates": "",
                "disableWeekends": false,
                "disableWeekdays": false,
                "disableFunction": "",
                "maxDate": null
              },
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "timezone": "",
              "datepickerMode": "day",
              "id": "ehn3fg",
              "hideOnChildrenHidden": false
            }
          ],
          "offset": 0,
          "push": 0,
          "pull": 0,
          "width": 4
        },
        {
          "components": [
            {
              "label": "Clinical Stage",
              "labelPosition": "top",
              "widget": "choicesjs",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "autofocus": false,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "dataSrc": "url",
              "data": {
                "values": [
                  {}
                ],
                "resource": "",
                "headers": [
                  {
                    "key": "",
                    "value": ""
                  }
                ],
                "json": "",
                "url": " http://lamisplus.org/base-module/api/application-codesets/codesetGroup?codesetGroup=CLINICAL%20STAGE",
                "custom": ""
              },
              "valueProperty": "",
              "dataType": "",
              "template": "<span>{{ item.display }}</span>",
              "searchEnabled": true,
              "selectThreshold": 0.3,
              "readOnlyValue": false,
              "customOptions": {},
              "persistent": true,
              "protected": false,
              "dbIndex": false,
              "encrypted": false,
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": false,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "unique": false,
                "multiple": false,
                "strictDateValidation": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "clinic_stage",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "select",
              "indexeddb": {
                "filter": {}
              },
              "minSearch": 0,
              "limit": 100,
              "input": true,
              "disableLimit": false,
              "hideOnChildrenHidden": false,
              "prefix": "",
              "suffix": "",
              "refreshOn": "",
              "redrawOn": "",
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "clearOnRefresh": false,
              "lazyLoad": true,
              "filter": "",
              "searchField": "",
              "authenticate": false,
              "selectFields": "",
              "searchThreshold": 0.3,
              "fuseOptions": {
                "include": "score",
                "threshold": 0.3
              },
              "id": "e07irj",
              "defaultValue": {},
              "selectValues": "",
              "sort": ""
            }
          ],
          "offset": 0,
          "push": 0,
          "pull": 0,
          "width": 4
        }
      ],
      "autoAdjust": false,
      "hideOnChildrenHidden": false,
      "customClass": "",
      "hidden": false,
      "hideLabel": false,
      "tableView": false,
      "modalEdit": false,
      "key": "columns4",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "columns",
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": false,
      "refreshOn": "",
      "redrawOn": "",
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "tree": false,
      "id": "eo4838a",
      "path": "columns4"
    },
    {
      "label": "Columns",
      "columns": [
        {
          "components": [
            {
              "label": "Clinician Note",
              "labelPosition": "top",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {
                "type": "input"
              },
              "editor": "",
              "autoExpand": false,
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "persistent": true,
              "inputFormat": "html",
              "protected": false,
              "dbIndex": false,
              "case": "",
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": false,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "minWords": "",
                "maxWords": "",
                "strictDateValidation": false,
                "unique": false,
                "multiple": false
              },
              "unique": false,
              "errorLabel": "",
              "key": "note",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "textarea",
              "wysiwyg": false,
              "input": true,
              "refreshOn": "",
              "allowMultipleMasks": false,
              "mask": false,
              "inputType": "text",
              "inputMask": "",
              "id": "edb6dso",
              "defaultValue": "",
              "rows": 5,
              "hideOnChildrenHidden": false
            }
          ],
          "offset": 0,
          "push": 0,
          "pull": 0,
          "width": 8
        },
        {
          "components": [],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0
        }
      ],
      "autoAdjust": false,
      "hideOnChildrenHidden": false,
      "customClass": "",
      "hidden": false,
      "hideLabel": false,
      "tableView": false,
      "modalEdit": false,
      "key": "columns5",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "columns",
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": false,
      "refreshOn": "",
      "redrawOn": "",
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "tree": false,
      "id": "eih5j1",
      "path": "columns5"
    },
    {
      "type": "button",
      "label": "Submit",
      "key": "submit",
      "size": "md",
      "block": false,
      "action": "submit",
      "disableOnInvalid": true,
      "theme": "primary",
      "input": true,
      "placeholder": "",
      "prefix": "",
      "customClass": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "hidden": false,
      "clearOnHide": true,
      "refreshOn": "",
      "redrawOn": "",
      "tableView": false,
      "modalEdit": false,
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "hideLabel": false,
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "widget": {
        "type": "input"
      },
      "attributes": {},
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false,
        "unique": false,
        "multiple": false
      },
      "conditional": {
        "show": null,
        "when": null,
        "eq": ""
      },
      "overlay": {
        "style": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "properties": {},
      "allowMultipleMasks": false,
      "leftIcon": "",
      "rightIcon": "",
      "dataGridLabel": true,
      "id": "ejb9tao"
    }
  ]
}