export const data = {
    "display": "",
    "components": [
      {
        "label": "Occupation",
        "labelPosition": "top",
        "widget": "choicesjs",
        "placeholder": "",
        "description": "",
        "tooltip": "",
        "customClass": "",
        "tabindex": "",
        "hidden": false,
        "hideLabel": false,
        "autofocus": false,
        "disabled": false,
        "tableView": true,
        "modalEdit": false,
        "multiple": false,
        "dataSrc": "url",
        "data": {
          "resource": "",
          "json": "",
          "url": "${url}occupation/",
          "custom": "",
          "headers": [
            {
              "key": "",
              "value": ""
            }
          ],
          "values": []
        },
        "valueProperty": "",
        "dataType": "",
        "template": "<span>{{ item.label }}</span>",
        "searchEnabled": true,
        "selectThreshold": 0.3,
        "readOnlyValue": false,
        "customOptions": {},
        "persistent": true,
        "protected": false,
        "dbIndex": false,
        "encrypted": false,
        "clearOnHide": true,
        "customDefaultValue": "",
        "calculateValue": "",
        "allowCalculateOverride": false,
        "validateOn": "change",
        "validate": {
          "required": false,
          "customMessage": "",
          "custom": "",
          "customPrivate": false,
          "json": "",
          "strictDateValidation": false,
          "unique": false,
          "multiple": false
        },
        "unique": false,
        "errorLabel": "",
        "key": "occupation",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "select",
        "indexeddb": {
          "filter": {}
        },
        "minSearch": 0,
        "limit": 100,
        "input": true,
        "prefix": "",
        "suffix": "",
        "refreshOn": "",
        "redrawOn": "",
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "clearOnRefresh": false,
        "lazyLoad": true,
        "filter": "",
        "searchField": "",
        "authenticate": false,
        "selectFields": "",
        "searchThreshold": 0.3,
        "fuseOptions": {
          "include": "score",
          "threshold": 0.3
        },
        "id": "eo8s35f",
        "defaultValue": {},
        "selectValues": "",
        "disableLimit": false,
        "sort": ""
      },
      {
        "type": "button",
        "label": "Submit",
        "key": "submit",
        "size": "md",
        "block": false,
        "action": "submit",
        "disableOnInvalid": true,
        "theme": "primary",
        "input": true,
        "placeholder": "",
        "prefix": "",
        "customClass": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "hidden": false,
        "clearOnHide": true,
        "refreshOn": "",
        "redrawOn": "",
        "tableView": false,
        "modalEdit": false,
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "hideLabel": false,
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": {
          "type": "input"
        },
        "attributes": {},
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false,
          "unique": false,
          "multiple": false
        },
        "conditional": {
          "show": null,
          "when": null,
          "eq": ""
        },
        "overlay": {
          "style": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "properties": {},
        "allowMultipleMasks": false,
        "leftIcon": "",
        "rightIcon": "",
        "dataGridLabel": true,
        "id": "ee05vmi"
      }
    ]
  }