export const data = {
    "display": "wizard",
    "components": [
      {
        "title": "1. Clinic Visit",
        "label": "1. Clinic Visit",
        "type": "panel",
        "key": "page1",
        "components": [
          {
            "label": "Container",
            "tableView": false,
            "validate": {
              "unique": false,
              "multiple": false,
              "required": false,
              "custom": "",
              "customPrivate": false,
              "strictDateValidation": false
            },
            "key": "container",
            "type": "container",
            "input": true,
            "components": [
              {
                "label": "Header",
                "attrs": [
                  {
                    "attr": "",
                    "value": ""
                  }
                ],
                "content": "<span style=\"color:#B87108\">Visit Details</span>\n<hr>",
                "refreshOnChange": false,
                "tableView": false,
                "key": "header",
                "type": "htmlelement",
                "input": false,
                "validate": {
                  "unique": false,
                  "multiple": false,
                  "required": false,
                  "custom": "",
                  "customPrivate": false,
                  "strictDateValidation": false
                },
                "placeholder": "",
                "prefix": "",
                "customClass": "",
                "suffix": "",
                "multiple": false,
                "defaultValue": null,
                "protected": false,
                "unique": false,
                "persistent": false,
                "hidden": false,
                "clearOnHide": true,
                "refreshOn": "",
                "redrawOn": "",
                "modalEdit": false,
                "labelPosition": "top",
                "description": "",
                "errorLabel": "",
                "tooltip": "",
                "hideLabel": false,
                "tabindex": "",
                "disabled": false,
                "autofocus": false,
                "dbIndex": false,
                "customDefaultValue": "",
                "calculateValue": "",
                "widget": null,
                "attributes": {},
                "validateOn": "change",
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": ""
                },
                "overlay": {
                  "style": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "allowCalculateOverride": false,
                "encrypted": false,
                "showCharCount": false,
                "showWordCount": false,
                "properties": {},
                "allowMultipleMasks": false,
                "tag": "p",
                "id": "e4agjcc"
              },
              {
                "label": "Columns",
                "columns": [
                  {
                    "components": [
                      {
                        "label": "Date Of Visit",
                        "format": "yyyy-MM-dd ",
                        "placeholder": "Enter visit date",
                        "tableView": false,
                        "datePicker": {
                          "disableWeekends": false,
                          "disableWeekdays": false,
                          "showWeeks": true,
                          "startingDay": 0,
                          "initDate": "",
                          "minMode": "day",
                          "maxMode": "year",
                          "yearRows": 4,
                          "yearColumns": 5,
                          "minDate": null,
                          "maxDate": null
                        },
                        "enableTime": false,
                        "validate": {
                          "required": true,
                          "unique": false,
                          "multiple": false,
                          "custom": "",
                          "customPrivate": false,
                          "strictDateValidation": false
                        },
                        "key": "dateOfVisit",
                        "type": "datetime",
                        "input": true,
                        "suffix": "<i ref=\"icon\" class=\"fa fa-calendar\" style=\"\"></i>",
                        "widget": {
                          "type": "calendar",
                          "displayInTimezone": "viewer",
                          "language": "en",
                          "useLocaleSettings": false,
                          "allowInput": true,
                          "mode": "single",
                          "enableTime": false,
                          "noCalendar": false,
                          "format": "yyyy-MM-dd ",
                          "hourIncrement": 1,
                          "minuteIncrement": 1,
                          "time_24hr": false,
                          "minDate": null,
                          "disableWeekends": false,
                          "disableWeekdays": false,
                          "maxDate": null
                        },
                        "prefix": "",
                        "customClass": "",
                        "multiple": false,
                        "defaultValue": "",
                        "protected": false,
                        "unique": false,
                        "persistent": true,
                        "hidden": false,
                        "clearOnHide": true,
                        "refreshOn": "",
                        "redrawOn": "",
                        "modalEdit": false,
                        "labelPosition": "top",
                        "description": "",
                        "errorLabel": "",
                        "tooltip": "",
                        "hideLabel": false,
                        "tabindex": "",
                        "disabled": false,
                        "autofocus": false,
                        "dbIndex": false,
                        "customDefaultValue": "",
                        "calculateValue": "",
                        "attributes": {},
                        "validateOn": "change",
                        "conditional": {
                          "show": null,
                          "when": null,
                          "eq": ""
                        },
                        "overlay": {
                          "style": "",
                          "left": "",
                          "top": "",
                          "width": "",
                          "height": ""
                        },
                        "allowCalculateOverride": false,
                        "encrypted": false,
                        "showCharCount": false,
                        "showWordCount": false,
                        "properties": {},
                        "allowMultipleMasks": false,
                        "useLocaleSettings": false,
                        "allowInput": true,
                        "enableDate": true,
                        "defaultDate": "",
                        "displayInTimezone": "viewer",
                        "timezone": "",
                        "datepickerMode": "day",
                        "timePicker": {
                          "hourStep": 1,
                          "minuteStep": 1,
                          "showMeridian": true,
                          "readonlyInput": false,
                          "mousewheel": true,
                          "arrowkeys": true
                        },
                        "customOptions": {},
                        "id": "egw4ta",
                        "hideOnChildrenHidden": false
                      }
                    ],
                    "width": 6,
                    "offset": 0,
                    "push": 0,
                    "pull": 0
                  },
                  {
                    "components": [],
                    "width": 6,
                    "offset": 0,
                    "push": 0,
                    "pull": 0
                  }
                ],
                "autoAdjust": false,
                "hideOnChildrenHidden": false,
                "customClass": "",
                "hidden": false,
                "hideLabel": false,
                "tableView": false,
                "modalEdit": false,
                "key": "columns",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "columns",
                "input": false,
                "placeholder": "",
                "prefix": "",
                "suffix": "",
                "multiple": false,
                "defaultValue": null,
                "protected": false,
                "unique": false,
                "persistent": false,
                "clearOnHide": false,
                "refreshOn": "",
                "redrawOn": "",
                "labelPosition": "top",
                "description": "",
                "errorLabel": "",
                "tooltip": "",
                "tabindex": "",
                "disabled": false,
                "autofocus": false,
                "dbIndex": false,
                "customDefaultValue": "",
                "calculateValue": "",
                "widget": null,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "custom": "",
                  "customPrivate": false,
                  "strictDateValidation": false
                },
                "allowCalculateOverride": false,
                "encrypted": false,
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "tree": false,
                "id": "eeihdis"
              },
              {
                "label": "Header",
                "attrs": [
                  {
                    "attr": "",
                    "value": ""
                  }
                ],
                "content": "<span style=\"color:#B87108\">Vital Signs</span>\n<hr>",
                "refreshOnChange": false,
                "tableView": false,
                "key": "header3",
                "type": "htmlelement",
                "input": false,
                "validate": {
                  "unique": false,
                  "multiple": false,
                  "required": false,
                  "custom": "",
                  "customPrivate": false,
                  "strictDateValidation": false
                },
                "placeholder": "",
                "prefix": "",
                "customClass": "",
                "suffix": "",
                "multiple": false,
                "defaultValue": null,
                "protected": false,
                "unique": false,
                "persistent": false,
                "hidden": false,
                "clearOnHide": true,
                "refreshOn": "",
                "redrawOn": "",
                "modalEdit": false,
                "labelPosition": "top",
                "description": "",
                "errorLabel": "",
                "tooltip": "",
                "hideLabel": false,
                "tabindex": "",
                "disabled": false,
                "autofocus": false,
                "dbIndex": false,
                "customDefaultValue": "",
                "calculateValue": "",
                "widget": null,
                "attributes": {},
                "validateOn": "change",
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": ""
                },
                "overlay": {
                  "style": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "allowCalculateOverride": false,
                "encrypted": false,
                "showCharCount": false,
                "showWordCount": false,
                "properties": {},
                "allowMultipleMasks": false,
                "tag": "p",
                "id": "eoh85k"
              },
              {
                "label": "vColumns",
                "columns": [
                  {
                    "components": [
                      {
                        "label": "Weight(kg)",
                        "labelPosition": "top",
                        "placeholder": "",
                        "description": "",
                        "tooltip": "",
                        "prefix": "",
                        "suffix": "",
                        "widget": {
                          "type": "input"
                        },
                        "inputMask": "",
                        "allowMultipleMasks": false,
                        "customClass": "",
                        "tabindex": "",
                        "hidden": false,
                        "hideLabel": false,
                        "showWordCount": false,
                        "showCharCount": false,
                        "mask": false,
                        "autofocus": false,
                        "spellcheck": true,
                        "disabled": false,
                        "tableView": true,
                        "modalEdit": false,
                        "multiple": false,
                        "persistent": true,
                        "inputFormat": "plain",
                        "protected": false,
                        "dbIndex": false,
                        "case": "",
                        "encrypted": false,
                        "redrawOn": "",
                        "clearOnHide": true,
                        "customDefaultValue": "",
                        "calculateValue": "",
                        "allowCalculateOverride": false,
                        "validateOn": "change",
                        "validate": {
                          "required": false,
                          "pattern": "",
                          "customMessage": "",
                          "custom": "",
                          "customPrivate": false,
                          "json": "",
                          "minLength": "",
                          "maxLength": "",
                          "strictDateValidation": false,
                          "unique": false,
                          "multiple": false
                        },
                        "unique": false,
                        "errorLabel": "",
                        "key": "weight",
                        "tags": [],
                        "properties": {},
                        "conditional": {
                          "show": null,
                          "when": null,
                          "eq": "",
                          "json": ""
                        },
                        "customConditional": "",
                        "logic": [],
                        "attributes": {},
                        "overlay": {
                          "style": "",
                          "page": "",
                          "left": "",
                          "top": "",
                          "width": "",
                          "height": ""
                        },
                        "type": "textfield",
                        "input": true,
                        "refreshOn": "",
                        "inputType": "text",
                        "id": "ebz0jkk",
                        "defaultValue": "",
                        "hideOnChildrenHidden": false
                      }
                    ],
                    "width": 3,
                    "offset": 0,
                    "push": 0,
                    "pull": 0
                  },
                  {
                    "components": [
                      {
                        "label": "Height(m)",
                        "labelPosition": "top",
                        "placeholder": "",
                        "description": "",
                        "tooltip": "",
                        "prefix": "",
                        "suffix": "",
                        "widget": {
                          "type": "input"
                        },
                        "inputMask": "",
                        "allowMultipleMasks": false,
                        "customClass": "",
                        "tabindex": "",
                        "hidden": false,
                        "hideLabel": false,
                        "showWordCount": false,
                        "showCharCount": false,
                        "mask": false,
                        "autofocus": false,
                        "spellcheck": true,
                        "disabled": false,
                        "tableView": true,
                        "modalEdit": false,
                        "multiple": false,
                        "persistent": true,
                        "inputFormat": "plain",
                        "protected": false,
                        "dbIndex": false,
                        "case": "",
                        "encrypted": false,
                        "redrawOn": "",
                        "clearOnHide": true,
                        "customDefaultValue": "",
                        "calculateValue": "",
                        "allowCalculateOverride": false,
                        "validateOn": "change",
                        "validate": {
                          "required": false,
                          "pattern": "",
                          "customMessage": "",
                          "custom": "",
                          "customPrivate": false,
                          "json": "",
                          "minLength": "",
                          "maxLength": "",
                          "strictDateValidation": false,
                          "unique": false,
                          "multiple": false
                        },
                        "unique": false,
                        "errorLabel": "",
                        "key": "height",
                        "tags": [],
                        "properties": {},
                        "conditional": {
                          "show": null,
                          "when": null,
                          "eq": "",
                          "json": ""
                        },
                        "customConditional": "",
                        "logic": [],
                        "attributes": {},
                        "overlay": {
                          "style": "",
                          "page": "",
                          "left": "",
                          "top": "",
                          "width": "",
                          "height": ""
                        },
                        "type": "textfield",
                        "input": true,
                        "refreshOn": "",
                        "inputType": "text",
                        "id": "ergglpu",
                        "defaultValue": "",
                        "hideOnChildrenHidden": false
                      }
                    ],
                    "width": 3,
                    "offset": 0,
                    "push": 0,
                    "pull": 0
                  },
                  {
                    "components": [
                      {
                        "label": "Diastolic(mmHg)",
                        "labelPosition": "top",
                        "placeholder": "",
                        "description": "",
                        "tooltip": "",
                        "prefix": "",
                        "suffix": "",
                        "widget": {
                          "type": "input"
                        },
                        "inputMask": "",
                        "allowMultipleMasks": false,
                        "customClass": "",
                        "tabindex": "",
                        "hidden": false,
                        "hideLabel": false,
                        "showWordCount": false,
                        "showCharCount": false,
                        "mask": false,
                        "autofocus": false,
                        "spellcheck": true,
                        "disabled": false,
                        "tableView": true,
                        "modalEdit": false,
                        "multiple": false,
                        "persistent": true,
                        "inputFormat": "plain",
                        "protected": false,
                        "dbIndex": false,
                        "case": "",
                        "encrypted": false,
                        "redrawOn": "",
                        "clearOnHide": true,
                        "customDefaultValue": "",
                        "calculateValue": "",
                        "allowCalculateOverride": false,
                        "validateOn": "change",
                        "validate": {
                          "required": false,
                          "pattern": "",
                          "customMessage": "",
                          "custom": "",
                          "customPrivate": false,
                          "json": "",
                          "minLength": "",
                          "maxLength": "",
                          "strictDateValidation": false,
                          "unique": false,
                          "multiple": false
                        },
                        "unique": false,
                        "errorLabel": "",
                        "key": "diastolic",
                        "tags": [],
                        "properties": {},
                        "conditional": {
                          "show": null,
                          "when": null,
                          "eq": "",
                          "json": ""
                        },
                        "customConditional": "",
                        "logic": [],
                        "attributes": {},
                        "overlay": {
                          "style": "",
                          "page": "",
                          "left": "",
                          "top": "",
                          "width": "",
                          "height": ""
                        },
                        "type": "textfield",
                        "input": true,
                        "refreshOn": "",
                        "inputType": "text",
                        "id": "etx8bgc",
                        "defaultValue": "",
                        "hideOnChildrenHidden": false
                      }
                    ],
                    "width": 2,
                    "offset": 0,
                    "push": 0,
                    "pull": 0
                  },
                  {
                    "components": [
                      {
                        "label": "HTML",
                        "tag": "p",
                        "className": "",
                        "attrs": [
                          {
                            "attr": "",
                            "value": ""
                          }
                        ],
                        "content": "/",
                        "refreshOnChange": false,
                        "customClass": "",
                        "hidden": false,
                        "tableView": false,
                        "modalEdit": false,
                        "key": "html1",
                        "tags": [],
                        "properties": {},
                        "conditional": {
                          "show": null,
                          "when": null,
                          "eq": "",
                          "json": ""
                        },
                        "customConditional": "",
                        "logic": [],
                        "attributes": {},
                        "overlay": {
                          "style": "",
                          "page": "",
                          "left": "",
                          "top": "",
                          "width": "",
                          "height": ""
                        },
                        "type": "htmlelement",
                        "input": false,
                        "placeholder": "",
                        "prefix": "",
                        "suffix": "",
                        "multiple": false,
                        "defaultValue": null,
                        "protected": false,
                        "unique": false,
                        "persistent": false,
                        "clearOnHide": true,
                        "refreshOn": "",
                        "redrawOn": "",
                        "labelPosition": "top",
                        "description": "",
                        "errorLabel": "",
                        "tooltip": "",
                        "hideLabel": false,
                        "tabindex": "",
                        "disabled": false,
                        "autofocus": false,
                        "dbIndex": false,
                        "customDefaultValue": "",
                        "calculateValue": "",
                        "widget": null,
                        "validateOn": "change",
                        "validate": {
                          "required": false,
                          "custom": "",
                          "customPrivate": false,
                          "strictDateValidation": false,
                          "unique": false,
                          "multiple": false
                        },
                        "allowCalculateOverride": false,
                        "encrypted": false,
                        "showCharCount": false,
                        "showWordCount": false,
                        "allowMultipleMasks": false,
                        "id": "esqcvlq",
                        "hideOnChildrenHidden": false
                      }
                    ],
                    "width": 1,
                    "offset": 0,
                    "push": 0,
                    "pull": 0
                  },
                  {
                    "components": [
                      {
                        "label": "Systolic(mmHg)",
                        "labelPosition": "top",
                        "placeholder": "",
                        "description": "",
                        "tooltip": "",
                        "prefix": "",
                        "suffix": "",
                        "widget": {
                          "type": "input"
                        },
                        "inputMask": "",
                        "allowMultipleMasks": false,
                        "customClass": "",
                        "tabindex": "",
                        "hidden": false,
                        "hideLabel": false,
                        "showWordCount": false,
                        "showCharCount": false,
                        "mask": false,
                        "autofocus": false,
                        "spellcheck": true,
                        "disabled": false,
                        "tableView": true,
                        "modalEdit": false,
                        "multiple": false,
                        "persistent": true,
                        "inputFormat": "plain",
                        "protected": false,
                        "dbIndex": false,
                        "case": "",
                        "encrypted": false,
                        "redrawOn": "",
                        "clearOnHide": true,
                        "customDefaultValue": "",
                        "calculateValue": "",
                        "allowCalculateOverride": false,
                        "validateOn": "change",
                        "validate": {
                          "required": false,
                          "pattern": "",
                          "customMessage": "",
                          "custom": "",
                          "customPrivate": false,
                          "json": "",
                          "minLength": "",
                          "maxLength": "",
                          "strictDateValidation": false,
                          "unique": false,
                          "multiple": false
                        },
                        "unique": false,
                        "errorLabel": "",
                        "key": "systolic",
                        "tags": [],
                        "properties": {},
                        "conditional": {
                          "show": null,
                          "when": null,
                          "eq": "",
                          "json": ""
                        },
                        "customConditional": "",
                        "logic": [],
                        "attributes": {},
                        "overlay": {
                          "style": "",
                          "page": "",
                          "left": "",
                          "top": "",
                          "width": "",
                          "height": ""
                        },
                        "type": "textfield",
                        "input": true,
                        "refreshOn": "",
                        "inputType": "text",
                        "id": "eqrhcbe",
                        "defaultValue": "",
                        "hideOnChildrenHidden": false
                      }
                    ],
                    "width": 2,
                    "offset": 0,
                    "push": 0,
                    "pull": 0
                  }
                ],
                "autoAdjust": false,
                "hideOnChildrenHidden": false,
                "customClass": "",
                "hidden": false,
                "hideLabel": false,
                "tableView": false,
                "modalEdit": false,
                "key": "vcolumns",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "columns",
                "input": false,
                "placeholder": "",
                "prefix": "",
                "suffix": "",
                "multiple": false,
                "defaultValue": null,
                "protected": false,
                "unique": false,
                "persistent": false,
                "clearOnHide": false,
                "refreshOn": "",
                "redrawOn": "",
                "labelPosition": "top",
                "description": "",
                "errorLabel": "",
                "tooltip": "",
                "tabindex": "",
                "disabled": false,
                "autofocus": false,
                "dbIndex": false,
                "customDefaultValue": "",
                "calculateValue": "",
                "widget": null,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "custom": "",
                  "customPrivate": false,
                  "strictDateValidation": false
                },
                "allowCalculateOverride": false,
                "encrypted": false,
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "tree": false,
                "id": "en5i31i"
              },
              {
                "label": "Header",
                "attrs": [
                  {
                    "attr": "",
                    "value": ""
                  }
                ],
                "content": "<span style=\"color:#B87108\">Population Information</span>\n<hr>",
                "refreshOnChange": false,
                "tableView": false,
                "key": "header2",
                "type": "htmlelement",
                "input": false,
                "validate": {
                  "unique": false,
                  "multiple": false,
                  "required": false,
                  "custom": "",
                  "customPrivate": false,
                  "strictDateValidation": false
                },
                "placeholder": "",
                "prefix": "",
                "customClass": "",
                "suffix": "",
                "multiple": false,
                "defaultValue": null,
                "protected": false,
                "unique": false,
                "persistent": false,
                "hidden": false,
                "clearOnHide": true,
                "refreshOn": "",
                "redrawOn": "",
                "modalEdit": false,
                "labelPosition": "top",
                "description": "",
                "errorLabel": "",
                "tooltip": "",
                "hideLabel": false,
                "tabindex": "",
                "disabled": false,
                "autofocus": false,
                "dbIndex": false,
                "customDefaultValue": "",
                "calculateValue": "",
                "widget": null,
                "attributes": {},
                "validateOn": "change",
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": ""
                },
                "overlay": {
                  "style": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "allowCalculateOverride": false,
                "encrypted": false,
                "showCharCount": false,
                "showWordCount": false,
                "properties": {},
                "allowMultipleMasks": false,
                "tag": "p",
                "id": "evkzyrm"
              },
              {
                "label": "Population Type",
                "optionsLabelPosition": "right",
                "inline": false,
                "hidden": false,
                "tableView": false,
                "values": [
                  {
                    "label": "General Population",
                    "value": "generalPopulation",
                    "shortcut": ""
                  },
                  {
                    "label": "Key Population",
                    "value": "keyPopulation",
                    "shortcut": ""
                  }
                ],
                "validate": {
                  "unique": false,
                  "multiple": false,
                  "required": false,
                  "custom": "",
                  "customPrivate": false,
                  "strictDateValidation": false
                },
                "key": "populationType",
                "tags": [
                  "populationType"
                ],
                "type": "radio",
                "input": true,
                "placeholder": "",
                "prefix": "",
                "customClass": "",
                "suffix": "",
                "multiple": false,
                "defaultValue": null,
                "protected": false,
                "unique": false,
                "persistent": true,
                "clearOnHide": true,
                "refreshOn": "",
                "redrawOn": "",
                "modalEdit": false,
                "labelPosition": "top",
                "description": "",
                "errorLabel": "",
                "tooltip": "",
                "hideLabel": false,
                "tabindex": "",
                "disabled": false,
                "autofocus": false,
                "dbIndex": false,
                "customDefaultValue": "",
                "calculateValue": "",
                "widget": null,
                "attributes": {},
                "validateOn": "change",
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": ""
                },
                "overlay": {
                  "style": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "allowCalculateOverride": false,
                "encrypted": false,
                "showCharCount": false,
                "showWordCount": false,
                "properties": {},
                "allowMultipleMasks": false,
                "inputType": "radio",
                "fieldSet": false,
                "id": "etx9si"
              },
              {
                "label": "Container",
                "tableView": false,
                "validate": {
                  "unique": false,
                  "multiple": false,
                  "required": false,
                  "custom": "",
                  "customPrivate": false,
                  "strictDateValidation": false
                },
                "key": "kpTypes",
                "type": "container",
                "input": true,
                "components": [
                  {
                    "label": "Columns",
                    "columns": [
                      {
                        "components": [
                          {
                            "label": "MSM",
                            "tableView": false,
                            "validate": {
                              "unique": false,
                              "multiple": false,
                              "required": false,
                              "custom": "",
                              "customPrivate": false,
                              "strictDateValidation": false
                            },
                            "key": "msm",
                            "type": "checkbox",
                            "input": true,
                            "defaultValue": false,
                            "hideOnChildrenHidden": false,
                            "placeholder": "",
                            "prefix": "",
                            "customClass": "",
                            "suffix": "",
                            "multiple": false,
                            "protected": false,
                            "unique": false,
                            "persistent": true,
                            "hidden": false,
                            "clearOnHide": true,
                            "refreshOn": "",
                            "redrawOn": "",
                            "modalEdit": false,
                            "labelPosition": "right",
                            "description": "",
                            "errorLabel": "",
                            "tooltip": "",
                            "hideLabel": false,
                            "tabindex": "",
                            "disabled": false,
                            "autofocus": false,
                            "dbIndex": false,
                            "customDefaultValue": "",
                            "calculateValue": "",
                            "widget": null,
                            "attributes": {},
                            "validateOn": "change",
                            "conditional": {
                              "show": null,
                              "when": null,
                              "eq": ""
                            },
                            "overlay": {
                              "style": "",
                              "left": "",
                              "top": "",
                              "width": "",
                              "height": ""
                            },
                            "allowCalculateOverride": false,
                            "encrypted": false,
                            "showCharCount": false,
                            "showWordCount": false,
                            "properties": {},
                            "allowMultipleMasks": false,
                            "inputType": "checkbox",
                            "dataGridLabel": true,
                            "value": "",
                            "name": "",
                            "id": "eyyq6eq"
                          }
                        ],
                        "width": 2,
                        "offset": 0,
                        "push": 0,
                        "pull": 0
                      },
                      {
                        "components": [
                          {
                            "label": "FSW",
                            "tableView": false,
                            "validate": {
                              "unique": false,
                              "multiple": false,
                              "required": false,
                              "custom": "",
                              "customPrivate": false,
                              "strictDateValidation": false
                            },
                            "key": "fsw",
                            "type": "checkbox",
                            "input": true,
                            "defaultValue": false,
                            "hideOnChildrenHidden": false,
                            "placeholder": "",
                            "prefix": "",
                            "customClass": "",
                            "suffix": "",
                            "multiple": false,
                            "protected": false,
                            "unique": false,
                            "persistent": true,
                            "hidden": false,
                            "clearOnHide": true,
                            "refreshOn": "",
                            "redrawOn": "",
                            "modalEdit": false,
                            "labelPosition": "right",
                            "description": "",
                            "errorLabel": "",
                            "tooltip": "",
                            "hideLabel": false,
                            "tabindex": "",
                            "disabled": false,
                            "autofocus": false,
                            "dbIndex": false,
                            "customDefaultValue": "",
                            "calculateValue": "",
                            "widget": null,
                            "attributes": {},
                            "validateOn": "change",
                            "conditional": {
                              "show": null,
                              "when": null,
                              "eq": ""
                            },
                            "overlay": {
                              "style": "",
                              "left": "",
                              "top": "",
                              "width": "",
                              "height": ""
                            },
                            "allowCalculateOverride": false,
                            "encrypted": false,
                            "showCharCount": false,
                            "showWordCount": false,
                            "properties": {},
                            "allowMultipleMasks": false,
                            "inputType": "checkbox",
                            "dataGridLabel": true,
                            "value": "",
                            "name": "",
                            "id": "eqfbd2w"
                          }
                        ],
                        "width": 2,
                        "offset": 0,
                        "push": 0,
                        "pull": 0
                      },
                      {
                        "components": [
                          {
                            "label": "PWID",
                            "tableView": false,
                            "defaultValue": false,
                            "validate": {
                              "unique": false,
                              "multiple": false,
                              "required": false,
                              "custom": "",
                              "customPrivate": false,
                              "strictDateValidation": false
                            },
                            "key": "pwid",
                            "type": "checkbox",
                            "input": true,
                            "hideOnChildrenHidden": false,
                            "placeholder": "",
                            "prefix": "",
                            "customClass": "",
                            "suffix": "",
                            "multiple": false,
                            "protected": false,
                            "unique": false,
                            "persistent": true,
                            "hidden": false,
                            "clearOnHide": true,
                            "refreshOn": "",
                            "redrawOn": "",
                            "modalEdit": false,
                            "labelPosition": "right",
                            "description": "",
                            "errorLabel": "",
                            "tooltip": "",
                            "hideLabel": false,
                            "tabindex": "",
                            "disabled": false,
                            "autofocus": false,
                            "dbIndex": false,
                            "customDefaultValue": "",
                            "calculateValue": "",
                            "widget": null,
                            "attributes": {},
                            "validateOn": "change",
                            "conditional": {
                              "show": null,
                              "when": null,
                              "eq": ""
                            },
                            "overlay": {
                              "style": "",
                              "left": "",
                              "top": "",
                              "width": "",
                              "height": ""
                            },
                            "allowCalculateOverride": false,
                            "encrypted": false,
                            "showCharCount": false,
                            "showWordCount": false,
                            "properties": {},
                            "allowMultipleMasks": false,
                            "inputType": "checkbox",
                            "dataGridLabel": true,
                            "value": "",
                            "name": "",
                            "id": "ej9fzvy"
                          }
                        ],
                        "width": 2,
                        "offset": 0,
                        "push": 0,
                        "pull": 0
                      }
                    ],
                    "tableView": false,
                    "key": "columns1",
                    "type": "columns",
                    "input": false,
                    "placeholder": "",
                    "prefix": "",
                    "customClass": "",
                    "suffix": "",
                    "multiple": false,
                    "defaultValue": null,
                    "protected": false,
                    "unique": false,
                    "persistent": false,
                    "hidden": false,
                    "clearOnHide": false,
                    "refreshOn": "",
                    "redrawOn": "",
                    "modalEdit": false,
                    "labelPosition": "top",
                    "description": "",
                    "errorLabel": "",
                    "tooltip": "",
                    "hideLabel": false,
                    "tabindex": "",
                    "disabled": false,
                    "autofocus": false,
                    "dbIndex": false,
                    "customDefaultValue": "",
                    "calculateValue": "",
                    "widget": null,
                    "attributes": {},
                    "validateOn": "change",
                    "validate": {
                      "required": false,
                      "custom": "",
                      "customPrivate": false,
                      "strictDateValidation": false
                    },
                    "conditional": {
                      "show": null,
                      "when": null,
                      "eq": ""
                    },
                    "overlay": {
                      "style": "",
                      "left": "",
                      "top": "",
                      "width": "",
                      "height": ""
                    },
                    "allowCalculateOverride": false,
                    "encrypted": false,
                    "showCharCount": false,
                    "showWordCount": false,
                    "properties": {},
                    "allowMultipleMasks": false,
                    "tree": false,
                    "autoAdjust": false,
                    "hideOnChildrenHidden": false,
                    "id": "etb86hh"
                  }
                ],
                "path": "kpTypes",
                "placeholder": "",
                "prefix": "",
                "customClass": "",
                "suffix": "",
                "multiple": false,
                "defaultValue": null,
                "protected": false,
                "unique": false,
                "persistent": true,
                "hidden": false,
                "clearOnHide": true,
                "refreshOn": "",
                "redrawOn": "",
                "modalEdit": false,
                "labelPosition": "top",
                "description": "",
                "errorLabel": "",
                "tooltip": "",
                "hideLabel": true,
                "tabindex": "",
                "disabled": false,
                "autofocus": false,
                "dbIndex": false,
                "customDefaultValue": "",
                "calculateValue": "",
                "widget": null,
                "attributes": {},
                "validateOn": "change",
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": ""
                },
                "overlay": {
                  "style": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "allowCalculateOverride": false,
                "encrypted": false,
                "showCharCount": false,
                "showWordCount": false,
                "properties": {},
                "allowMultipleMasks": false,
                "tree": true,
                "id": "e3gutv6"
              },
              {
                "label": "Header",
                "attrs": [
                  {
                    "attr": "",
                    "value": ""
                  }
                ],
                "content": "<span style=\"color:#B87108\">WHO Staging</span>\n<hr>",
                "refreshOnChange": false,
                "tableView": false,
                "key": "header4",
                "type": "htmlelement",
                "input": false,
                "validate": {
                  "unique": false,
                  "multiple": false,
                  "required": false,
                  "custom": "",
                  "customPrivate": false,
                  "strictDateValidation": false
                },
                "placeholder": "",
                "prefix": "",
                "customClass": "",
                "suffix": "",
                "multiple": false,
                "defaultValue": null,
                "protected": false,
                "unique": false,
                "persistent": false,
                "hidden": false,
                "clearOnHide": true,
                "refreshOn": "",
                "redrawOn": "",
                "modalEdit": false,
                "labelPosition": "top",
                "description": "",
                "errorLabel": "",
                "tooltip": "",
                "hideLabel": false,
                "tabindex": "",
                "disabled": false,
                "autofocus": false,
                "dbIndex": false,
                "customDefaultValue": "",
                "calculateValue": "",
                "widget": null,
                "attributes": {},
                "validateOn": "change",
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": ""
                },
                "overlay": {
                  "style": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "allowCalculateOverride": false,
                "encrypted": false,
                "showCharCount": false,
                "showWordCount": false,
                "properties": {},
                "allowMultipleMasks": false,
                "tag": "p",
                "id": "eruslvq"
              },
              {
                "input": false,
                "key": "columns2",
                "tableView": false,
                "label": "Columns",
                "type": "columns",
                "columns": [
                  {
                    "components": [
                      {
                        "label": "WHO Stage",
                        "labelPosition": "top",
                        "widget": null,
                        "placeholder": "",
                        "description": "",
                        "tooltip": "",
                        "customClass": "",
                        "tabindex": "",
                        "hidden": false,
                        "hideLabel": false,
                        "autofocus": false,
                        "disabled": false,
                        "tableView": true,
                        "modalEdit": false,
                        "multiple": false,
                        "dataSrc": "values",
                        "data": {
                          "values": [
                            {
                              "label": "",
                              "value": ""
                            }
                          ],
                          "resource": "",
                          "json": "",
                          "url": "",
                          "custom": ""
                        },
                        "valueProperty": "",
                        "dataType": "",
                        "template": "<span>{{ item.label }}</span>",
                        "searchEnabled": true,
                        "selectThreshold": 0.3,
                        "readOnlyValue": false,
                        "customOptions": {},
                        "persistent": true,
                        "protected": false,
                        "dbIndex": false,
                        "encrypted": false,
                        "clearOnHide": true,
                        "customDefaultValue": "",
                        "calculateValue": "",
                        "allowCalculateOverride": false,
                        "validateOn": "change",
                        "validate": {
                          "required": false,
                          "customMessage": "",
                          "custom": "",
                          "customPrivate": false,
                          "json": "",
                          "strictDateValidation": false,
                          "unique": false,
                          "multiple": false
                        },
                        "unique": false,
                        "errorLabel": "",
                        "key": "whoStage",
                        "tags": [],
                        "properties": {},
                        "conditional": {
                          "show": null,
                          "when": null,
                          "eq": "",
                          "json": ""
                        },
                        "customConditional": "",
                        "logic": [],
                        "attributes": {},
                        "overlay": {
                          "style": "",
                          "page": "",
                          "left": "",
                          "top": "",
                          "width": "",
                          "height": ""
                        },
                        "type": "select",
                        "indexeddb": {
                          "filter": {}
                        },
                        "minSearch": 0,
                        "limit": 100,
                        "input": true,
                        "prefix": "",
                        "suffix": "",
                        "refreshOn": "",
                        "redrawOn": "",
                        "showCharCount": false,
                        "showWordCount": false,
                        "allowMultipleMasks": false,
                        "clearOnRefresh": false,
                        "lazyLoad": true,
                        "filter": "",
                        "searchField": "",
                        "authenticate": false,
                        "selectFields": "",
                        "searchThreshold": 0.3,
                        "fuseOptions": {
                          "include": "score",
                          "threshold": 0.3
                        },
                        "id": "e07i8ej",
                        "defaultValue": "",
                        "hideOnChildrenHidden": false
                      }
                    ],
                    "width": 6,
                    "offset": 0,
                    "push": 0,
                    "pull": 0
                  },
                  {
                    "components": [],
                    "width": 6,
                    "offset": 0,
                    "push": 0,
                    "pull": 0
                  }
                ],
                "placeholder": "",
                "prefix": "",
                "customClass": "",
                "suffix": "",
                "multiple": false,
                "defaultValue": null,
                "protected": false,
                "unique": false,
                "persistent": false,
                "hidden": false,
                "clearOnHide": false,
                "refreshOn": "",
                "redrawOn": "",
                "modalEdit": false,
                "labelPosition": "top",
                "description": "",
                "errorLabel": "",
                "tooltip": "",
                "hideLabel": false,
                "tabindex": "",
                "disabled": false,
                "autofocus": false,
                "dbIndex": false,
                "customDefaultValue": "",
                "calculateValue": "",
                "widget": null,
                "attributes": {},
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "custom": "",
                  "customPrivate": false,
                  "strictDateValidation": false
                },
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": ""
                },
                "overlay": {
                  "style": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "allowCalculateOverride": false,
                "encrypted": false,
                "showCharCount": false,
                "showWordCount": false,
                "properties": {},
                "allowMultipleMasks": false,
                "tree": false,
                "autoAdjust": false,
                "hideOnChildrenHidden": false,
                "id": "ev2y71d"
              }
            ],
            "path": "container",
            "placeholder": "",
            "prefix": "",
            "customClass": "",
            "suffix": "",
            "multiple": false,
            "defaultValue": null,
            "protected": false,
            "unique": false,
            "persistent": true,
            "hidden": false,
            "clearOnHide": true,
            "refreshOn": "",
            "redrawOn": "",
            "modalEdit": false,
            "labelPosition": "top",
            "description": "",
            "errorLabel": "",
            "tooltip": "",
            "hideLabel": true,
            "tabindex": "",
            "disabled": false,
            "autofocus": false,
            "dbIndex": false,
            "customDefaultValue": "",
            "calculateValue": "",
            "widget": null,
            "attributes": {},
            "validateOn": "change",
            "conditional": {
              "show": null,
              "when": null,
              "eq": ""
            },
            "overlay": {
              "style": "",
              "left": "",
              "top": "",
              "width": "",
              "height": ""
            },
            "allowCalculateOverride": false,
            "encrypted": false,
            "showCharCount": false,
            "showWordCount": false,
            "properties": {},
            "allowMultipleMasks": false,
            "tree": true,
            "id": "e4na3q"
          }
        ],
        "input": false,
        "placeholder": "",
        "prefix": "",
        "customClass": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "hidden": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "tableView": false,
        "modalEdit": false,
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "hideLabel": false,
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "attributes": {},
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "conditional": {
          "show": null,
          "when": null,
          "eq": ""
        },
        "overlay": {
          "style": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "properties": {},
        "allowMultipleMasks": false,
        "tree": false,
        "theme": "default",
        "breadcrumb": "default",
        "id": "evdjr7q"
      },
      {
        "title": "2. Consultation",
        "label": "2. Consultation",
        "type": "panel",
        "key": "page2",
        "components": [],
        "input": false,
        "placeholder": "",
        "prefix": "",
        "customClass": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "hidden": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "tableView": false,
        "modalEdit": false,
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "hideLabel": false,
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "attributes": {},
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "conditional": {
          "show": null,
          "when": null,
          "eq": ""
        },
        "overlay": {
          "style": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "properties": {},
        "allowMultipleMasks": false,
        "tree": false,
        "theme": "default",
        "breadcrumb": "default",
        "id": "egyhoho"
      }
    ]
  };
  