export const data = {
    "display": "form",
    "components": [
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Patient ID",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "inputMask": "",
                "allowMultipleMasks": false,
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "showWordCount": false,
                "showCharCount": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "case": "",
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": true,
                  "pattern": "",
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "minLength": "",
                  "maxLength": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "patientId",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "textfield",
                "input": true,
                "refreshOn": "",
                "inputType": "text",
                "id": "ey40kx",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "width": 4,
            "offset": 0,
            "push": 0,
            "pull": 0
          },
          {
            "components": [
              {
                "label": "Date Of Reg",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "<i ref=\"icon\" class=\"fa fa-calendar\" style=\"\"></i>",
                "widget": {
                  "type": "calendar",
                  "altInput": true,
                  "allowInput": true,
                  "clickOpens": true,
                  "enableDate": true,
                  "enableTime": true,
                  "mode": "single",
                  "noCalendar": false,
                  "format": "yyyy-MM-dd",
                  "dateFormat": "yyyy-MM-dd",
                  "useLocaleSettings": false,
                  "hourIncrement": 1,
                  "minuteIncrement": 5,
                  "time_24hr": false,
                  "saveAs": "date",
                  "displayInTimezone": "",
                  "timezone": "",
                  "disable": [],
                  "minDate": "",
                  "maxDate": ""
                },
                "inputMask": "",
                "allowMultipleMasks": false,
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "showWordCount": false,
                "showCharCount": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "case": "",
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": true,
                  "pattern": "",
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "minLength": "",
                  "maxLength": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "dateOfReg",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "textfield",
                "input": true,
                "refreshOn": "",
                "inputType": "text",
                "id": "eu1i02j",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "width": 4,
            "offset": 0,
            "push": 0,
            "pull": 0
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": true,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "emhdmhd",
        "path": "columns"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "First Name",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "inputMask": "",
                "allowMultipleMasks": false,
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "showWordCount": false,
                "showCharCount": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "case": "",
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "pattern": "",
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "minLength": "",
                  "maxLength": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "firstName",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "textfield",
                "input": true,
                "refreshOn": "",
                "inputType": "text",
                "id": "et7f0ik",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "width": 4,
            "offset": 0,
            "push": 0,
            "pull": 0
          },
          {
            "components": [
              {
                "label": "Other Name(s)",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "inputMask": "",
                "allowMultipleMasks": false,
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "showWordCount": false,
                "showCharCount": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "case": "",
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "pattern": "",
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "minLength": "",
                  "maxLength": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "otherNameS",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "textfield",
                "input": true,
                "refreshOn": "",
                "inputType": "text",
                "id": "eay0x54",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Last Name",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "inputMask": "",
                "allowMultipleMasks": false,
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "showWordCount": false,
                "showCharCount": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "case": "",
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "pattern": "",
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "minLength": "",
                  "maxLength": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "lastName",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "textfield",
                "input": true,
                "refreshOn": "",
                "inputType": "text",
                "id": "ekm12a",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns1",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "eoec5ln",
        "path": "columns1"
      },
      {
        "label": "Address",
        "customClass": "",
        "hidden": false,
        "disabled": false,
        "tableView": false,
        "modalEdit": false,
        "key": "address",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "well",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": true,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "hideLabel": false,
        "tabindex": "",
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "components": [
          {
            "label": "Columns",
            "columns": [
              {
                "components": [
                  {
                    "label": "Street Address",
                    "labelPosition": "top",
                    "placeholder": "",
                    "description": "",
                    "tooltip": "",
                    "prefix": "",
                    "suffix": "",
                    "widget": {
                      "type": "input"
                    },
                    "inputMask": "",
                    "allowMultipleMasks": false,
                    "customClass": "",
                    "tabindex": "",
                    "hidden": false,
                    "hideLabel": false,
                    "showWordCount": false,
                    "showCharCount": false,
                    "mask": false,
                    "autofocus": false,
                    "spellcheck": true,
                    "disabled": false,
                    "tableView": true,
                    "modalEdit": false,
                    "multiple": false,
                    "persistent": true,
                    "inputFormat": "plain",
                    "protected": false,
                    "dbIndex": false,
                    "case": "",
                    "encrypted": false,
                    "redrawOn": "",
                    "clearOnHide": true,
                    "customDefaultValue": "",
                    "calculateValue": "",
                    "allowCalculateOverride": false,
                    "validateOn": "change",
                    "validate": {
                      "required": false,
                      "pattern": "",
                      "customMessage": "",
                      "custom": "",
                      "customPrivate": false,
                      "json": "",
                      "minLength": "",
                      "maxLength": "",
                      "strictDateValidation": false,
                      "unique": false,
                      "multiple": false
                    },
                    "unique": false,
                    "errorLabel": "",
                    "key": "streetAddress",
                    "tags": [],
                    "properties": {},
                    "conditional": {
                      "show": null,
                      "when": null,
                      "eq": "",
                      "json": ""
                    },
                    "customConditional": "",
                    "logic": [],
                    "attributes": {},
                    "overlay": {
                      "style": "",
                      "page": "",
                      "left": "",
                      "top": "",
                      "width": "",
                      "height": ""
                    },
                    "type": "textfield",
                    "input": true,
                    "refreshOn": "",
                    "inputType": "text",
                    "id": "e2cjtr",
                    "defaultValue": "",
                    "hideOnChildrenHidden": false
                  },
                  {
                    "label": "Url",
                    "labelPosition": "top",
                    "placeholder": "",
                    "description": "",
                    "tooltip": "",
                    "prefix": "",
                    "suffix": "",
                    "widget": {
                      "type": "input"
                    },
                    "customClass": "",
                    "tabindex": "",
                    "hidden": false,
                    "hideLabel": false,
                    "mask": false,
                    "autofocus": false,
                    "spellcheck": true,
                    "disabled": false,
                    "tableView": true,
                    "modalEdit": false,
                    "multiple": false,
                    "persistent": true,
                    "inputFormat": "plain",
                    "protected": false,
                    "dbIndex": false,
                    "encrypted": false,
                    "redrawOn": "",
                    "clearOnHide": true,
                    "customDefaultValue": "",
                    "calculateValue": "",
                    "allowCalculateOverride": false,
                    "validateOn": "change",
                    "validate": {
                      "required": false,
                      "pattern": "",
                      "customMessage": "",
                      "custom": "",
                      "customPrivate": false,
                      "json": "",
                      "minLength": "",
                      "maxLength": "",
                      "strictDateValidation": false,
                      "unique": false,
                      "multiple": false
                    },
                    "unique": false,
                    "errorLabel": "",
                    "key": "url",
                    "tags": [],
                    "properties": {},
                    "conditional": {
                      "show": null,
                      "when": null,
                      "eq": "",
                      "json": ""
                    },
                    "customConditional": "",
                    "logic": [],
                    "attributes": {},
                    "overlay": {
                      "style": "",
                      "page": "",
                      "left": "",
                      "top": "",
                      "width": "",
                      "height": ""
                    },
                    "type": "url",
                    "input": true,
                    "refreshOn": "",
                    "showCharCount": false,
                    "showWordCount": false,
                    "allowMultipleMasks": false,
                    "inputType": "url",
                    "inputMask": "",
                    "id": "e8mod5g",
                    "hideOnChildrenHidden": false,
                    "defaultValue": null
                  }
                ],
                "width": 6,
                "offset": 0,
                "push": 0,
                "pull": 0
              },
              {
                "components": [
                  {
                    "label": "Landmark",
                    "labelPosition": "top",
                    "placeholder": "",
                    "description": "",
                    "tooltip": "",
                    "prefix": "",
                    "suffix": "",
                    "widget": {
                      "type": "input"
                    },
                    "inputMask": "",
                    "allowMultipleMasks": false,
                    "customClass": "",
                    "tabindex": "",
                    "hidden": false,
                    "hideLabel": false,
                    "showWordCount": false,
                    "showCharCount": false,
                    "mask": false,
                    "autofocus": false,
                    "spellcheck": true,
                    "disabled": false,
                    "tableView": true,
                    "modalEdit": false,
                    "multiple": false,
                    "persistent": true,
                    "inputFormat": "plain",
                    "protected": false,
                    "dbIndex": false,
                    "case": "",
                    "encrypted": false,
                    "redrawOn": "",
                    "clearOnHide": true,
                    "customDefaultValue": "",
                    "calculateValue": "",
                    "allowCalculateOverride": false,
                    "validateOn": "change",
                    "validate": {
                      "required": false,
                      "pattern": "",
                      "customMessage": "",
                      "custom": "",
                      "customPrivate": false,
                      "json": "",
                      "minLength": "",
                      "maxLength": "",
                      "strictDateValidation": false,
                      "unique": false,
                      "multiple": false
                    },
                    "unique": false,
                    "errorLabel": "",
                    "key": "landmark",
                    "tags": [],
                    "properties": {},
                    "conditional": {
                      "show": null,
                      "when": null,
                      "eq": "",
                      "json": ""
                    },
                    "customConditional": "",
                    "logic": [],
                    "attributes": {},
                    "overlay": {
                      "style": "",
                      "page": "",
                      "left": "",
                      "top": "",
                      "width": "",
                      "height": ""
                    },
                    "type": "textfield",
                    "input": true,
                    "refreshOn": "",
                    "inputType": "text",
                    "id": "e929db8",
                    "defaultValue": "",
                    "hideOnChildrenHidden": false
                  }
                ],
                "width": 6,
                "offset": 0,
                "push": 0,
                "pull": 0
              }
            ],
            "autoAdjust": false,
            "hideOnChildrenHidden": false,
            "customClass": "",
            "hidden": false,
            "hideLabel": false,
            "tableView": false,
            "modalEdit": false,
            "key": "columns2",
            "tags": [],
            "properties": {},
            "conditional": {
              "show": null,
              "when": null,
              "eq": "",
              "json": ""
            },
            "customConditional": "",
            "logic": [],
            "attributes": {},
            "overlay": {
              "style": "",
              "page": "",
              "left": "",
              "top": "",
              "width": "",
              "height": ""
            },
            "type": "columns",
            "input": false,
            "placeholder": "",
            "prefix": "",
            "suffix": "",
            "multiple": false,
            "defaultValue": null,
            "protected": false,
            "unique": false,
            "persistent": false,
            "clearOnHide": false,
            "refreshOn": "",
            "redrawOn": "",
            "labelPosition": "top",
            "description": "",
            "errorLabel": "",
            "tooltip": "",
            "tabindex": "",
            "disabled": false,
            "autofocus": false,
            "dbIndex": false,
            "customDefaultValue": "",
            "calculateValue": "",
            "widget": null,
            "validateOn": "change",
            "validate": {
              "required": false,
              "custom": "",
              "customPrivate": false,
              "strictDateValidation": false
            },
            "allowCalculateOverride": false,
            "encrypted": false,
            "showCharCount": false,
            "showWordCount": false,
            "allowMultipleMasks": false,
            "tree": false,
            "id": "en859uf",
            "path": "columns2"
          }
        ],
        "id": "ezmou1q",
        "hideOnChildrenHidden": false,
        "path": "address"
      },
      {
        "label": "Submit",
        "action": "submit",
        "showValidations": true,
        "theme": "primary",
        "size": "md",
        "block": false,
        "leftIcon": "",
        "rightIcon": "",
        "shortcut": "",
        "description": "",
        "tooltip": "",
        "customClass": "",
        "tabindex": "",
        "disableOnInvalid": true,
        "hidden": false,
        "autofocus": false,
        "disabled": false,
        "tableView": false,
        "modalEdit": false,
        "key": "submit",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "form.on('submit', function(submission) {\r\n      console.log(submission);\r\n      alert('Submission sent to custom endpoint. See developer console.');\r\n      return fetch('https://lamisplus.org/ZrRRbJBe', {\r\n          body: JSON.stringify(submission),\r\n          headers: {\r\n            'content-type': 'application/json'\r\n          },\r\n          method: 'POST',\r\n          mode: 'cors',\r\n        })\r\n        .then(response => {\r\n          form.emit('submitDone', submission)\r\n          response.json()\r\n        })\r\n    });",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "button",
        "url": "localhost:9009/whatevee",
        "headers": [
          {
            "header": "",
            "value": ""
          }
        ],
        "input": true,
        "validate": {
          "unique": false,
          "multiple": false,
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": true,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "errorLabel": "",
        "hideLabel": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": {
          "type": "input"
        },
        "validateOn": "change",
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "dataGridLabel": true,
        "id": "ejf3wjm"
      }
    ]
  };
