export const data = {
    "display": "form",
    "components": [
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Username",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "inputMask": "",
                "allowMultipleMasks": false,
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "showWordCount": false,
                "showCharCount": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "case": "",
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "pattern": "",
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "minLength": "",
                  "maxLength": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "username",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "textfield",
                "input": true,
                "refreshOn": "",
                "inputType": "text",
                "id": "e11na3k",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "width": 6,
            "offset": 0,
            "push": 0,
            "pull": 0
          },
          {
            "components": [
              {
                "label": "Email (Gmail)",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "case": "",
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "pattern": "",
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "minLength": "",
                  "maxLength": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "kickbox": {
                  "enabled": false
                },
                "errorLabel": "",
                "key": "email",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "email",
                "input": true,
                "refreshOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "inputType": "email",
                "inputMask": "",
                "id": "e7ronw",
                "defaultValue": "",
                "hideOnChildrenHidden": false
              }
            ],
            "width": 3,
            "offset": 0,
            "push": 0,
            "pull": 0
          },
          {
            "components": [],
            "width": 3,
            "offset": 0,
            "push": 0,
            "pull": 0
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "e3inqn5",
        "path": "columns"
      },
      {
        "label": "Login",
        "action": "submit",
        "showValidations": false,
        "theme": "primary",
        "size": "md",
        "block": false,
        "leftIcon": "",
        "rightIcon": "",
        "shortcut": "",
        "description": "",
        "tooltip": "",
        "customClass": "",
        "tabindex": "",
        "disableOnInvalid": false,
        "hidden": false,
        "autofocus": false,
        "disabled": false,
        "tableView": false,
        "modalEdit": false,
        "key": "login",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "button",
        "input": true,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": true,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "errorLabel": "",
        "hideLabel": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": {
          "type": "input"
        },
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false,
          "unique": false,
          "multiple": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "dataGridLabel": true,
        "id": "eiqninb",
        "hideOnChildrenHidden": false
      }
    ]
  };