export const data = {
    "display": "",
    "components": [
      {
        "label": "Differentiated Care",
        "tag": "p",
        "className": "",
        "attrs": [
          {
            "attr": "",
            "value": ""
          }
        ],
        "content": "<span style=\"color:#B87108\">DIFFERIENTIATED CARE</span>\n<hr>",
        "refreshOnChange": false,
        "customClass": "",
        "hidden": false,
        "tableView": false,
        "modalEdit": false,
        "key": "differentiated_care",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "htmlelement",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": true,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "hideLabel": false,
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false,
          "unique": false,
          "multiple": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "id": "eilzwy"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Date of Devolvement ",
                "labelPosition": "top",
                "displayInTimezone": "viewer",
                "useLocaleSettings": true,
                "allowInput": false,
                "format": "yyyy-MM-dd ",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": false,
                "modalEdit": false,
                "enableDate": true,
                "datePicker": {
                  "minDate": null,
                  "maxDate": null,
                  "disable": "",
                  "disableFunction": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "showWeeks": true,
                  "startingDay": 0,
                  "initDate": "",
                  "minMode": "day",
                  "maxMode": "year",
                  "yearRows": 4,
                  "yearColumns": 5
                },
                "enableTime": true,
                "timePicker": {
                  "showMeridian": true,
                  "hourStep": 1,
                  "minuteStep": 1,
                  "readonlyInput": false,
                  "mousewheel": true,
                  "arrowkeys": true
                },
                "multiple": false,
                "defaultValue": "",
                "defaultDate": "",
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validate": {
                  "required": true,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "validateOn": "change",
                "errorLabel": "",
                "key": "date_devolved",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "datetime",
                "input": true,
                "prefix": "",
                "suffix": "<i ref=\"icon\" class=\"fa fa-calendar\" style=\"\"></i>",
                "refreshOn": "",
                "widget": {
                  "type": "calendar",
                  "displayInTimezone": "viewer",
                  "language": "en",
                  "useLocaleSettings": true,
                  "allowInput": false,
                  "mode": "single",
                  "enableTime": true,
                  "noCalendar": false,
                  "format": "yyyy-MM-dd ",
                  "hourIncrement": 1,
                  "minuteIncrement": 1,
                  "time_24hr": false,
                  "minDate": null,
                  "disabledDates": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "disableFunction": "",
                  "maxDate": null
                },
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "timezone": "",
                "datepickerMode": "day",
                "id": "eqz96n",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Type of DMOC",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "url",
                "data": {
                  "values": [
                    {}
                  ],
                  "resource": "",
                  "url": "http://lamisplus.org/base-module/api/application-codesets/codesetGroup?codesetGroup=Type%20of%20DMOC",
                  "headers": [
                    {
                      "key": "",
                      "value": ""
                    }
                  ],
                  "json": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.display }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "unique": false,
                  "multiple": false,
                  "strictDateValidation": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "type_dmoc",
                "tags": [],
                "properties": {
                  "": "yes",
                  "CPARP": "yes",
                  "MMS": "yes",
                  "MMD": "yes",
                  "key": ""
                },
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {
                  "Type of DMOC": "CPARP"
                },
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "disableLimit": false,
                "hideOnChildrenHidden": false,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "egsq1yt",
                "defaultValue": {}
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Type of Scripting",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "values",
                "data": {
                  "values": [
                    {
                      "label": "MMD3",
                      "value": "type_scripting"
                    },
                    {
                      "label": "MMD6",
                      "value": "type_scripting"
                    },
                    {
                      "label": "MMD12",
                      "value": "type_scripting"
                    },
                    {
                      "label": "MMS",
                      "value": "type_scripting"
                    }
                  ],
                  "resource": "",
                  "json": "",
                  "url": "",
                  "custom": ""
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.label }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "unique": false,
                  "multiple": false,
                  "strictDateValidation": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "type_scripting",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "hideOnChildrenHidden": false,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "etu7oc",
                "defaultValue": ""
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns5",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "el2rail",
        "path": "columns5"
      },
      {
        "title": "Details of community pharmacy/club providing arv",
        "theme": "default",
        "tooltip": "",
        "customClass": "",
        "collapsible": false,
        "hidden": false,
        "disabled": false,
        "tableView": false,
        "modalEdit": false,
        "key": "community_pharmacy",
        "tags": [],
        "properties": {},
        "customConditional": "console.log(data.type_dmoc.display); show = ( data.type_dmoc && data.type_dmoc.display === 'CPARP' )",
        "conditional": {
          "json": "",
          "show": null,
          "when": null,
          "eq": ""
        },
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "panel",
        "label": "Details of community pharmacy/club providing arv",
        "breadcrumb": "default",
        "input": false,
        "components": [
          {
            "label": "Columns",
            "columns": [
              {
                "components": [
                  {
                    "label": "State",
                    "widget": "choicesjs",
                    "tableView": true,
                    "dataSrc": "url",
                    "data": {
                      "values": [
                        {}
                      ],
                      "url": " http://lamisplus.org/base-module/api/state",
                      "headers": [
                        {
                          "key": "",
                          "value": ""
                        }
                      ],
                      "json": "",
                      "resource": "",
                      "custom": ""
                    },
                    "template": "<span>{{ item.name }}</span>",
                    "selectThreshold": 0.3,
                    "validate": {
                      "unique": false,
                      "multiple": false,
                      "required": false,
                      "custom": "",
                      "customPrivate": false,
                      "strictDateValidation": false
                    },
                    "key": "state",
                    "type": "select",
                    "indexeddb": {
                      "filter": {}
                    },
                    "input": true,
                    "disableLimit": false,
                    "hideOnChildrenHidden": false,
                    "placeholder": "",
                    "prefix": "",
                    "customClass": "",
                    "suffix": "",
                    "multiple": false,
                    "defaultValue": null,
                    "protected": false,
                    "unique": false,
                    "persistent": true,
                    "hidden": false,
                    "clearOnHide": true,
                    "refreshOn": "",
                    "redrawOn": "",
                    "modalEdit": false,
                    "labelPosition": "top",
                    "description": "",
                    "errorLabel": "",
                    "tooltip": "",
                    "hideLabel": false,
                    "tabindex": "",
                    "disabled": false,
                    "autofocus": false,
                    "dbIndex": false,
                    "customDefaultValue": "",
                    "calculateValue": "",
                    "attributes": {},
                    "validateOn": "change",
                    "conditional": {
                      "show": null,
                      "when": null,
                      "eq": ""
                    },
                    "overlay": {
                      "style": "",
                      "left": "",
                      "top": "",
                      "width": "",
                      "height": ""
                    },
                    "allowCalculateOverride": false,
                    "encrypted": false,
                    "showCharCount": false,
                    "showWordCount": false,
                    "properties": {},
                    "allowMultipleMasks": false,
                    "clearOnRefresh": false,
                    "limit": 100,
                    "valueProperty": "",
                    "lazyLoad": true,
                    "filter": "",
                    "searchEnabled": true,
                    "searchField": "",
                    "minSearch": 0,
                    "readOnlyValue": false,
                    "authenticate": false,
                    "selectFields": "",
                    "searchThreshold": 0.3,
                    "fuseOptions": {
                      "include": "score",
                      "threshold": 0.3
                    },
                    "customOptions": {},
                    "id": "eql75mh"
                  }
                ],
                "offset": 0,
                "push": 0,
                "pull": 0,
                "width": 4
              },
              {
                "components": [
                  {
                    "label": "Province/LGA",
                    "widget": "choicesjs",
                    "tableView": true,
                    "dataSrc": "url",
                    "data": {
                      "values": [
                        {}
                      ],
                      "url": "http://lamisplus.org/base-module/api/provinces/",
                      "headers": [
                        {
                          "key": "",
                          "value": ""
                        }
                      ],
                      "json": "",
                      "resource": "",
                      "custom": ""
                    },
                    "template": "<span>{{ item.name }}</span>",
                    "selectThreshold": 0.3,
                    "validate": {
                      "unique": false,
                      "multiple": false,
                      "required": false,
                      "custom": "",
                      "customPrivate": false,
                      "strictDateValidation": false
                    },
                    "key": "lga",
                    "type": "select",
                    "indexeddb": {
                      "filter": {}
                    },
                    "input": true,
                    "disableLimit": false,
                    "hideOnChildrenHidden": false,
                    "placeholder": "",
                    "prefix": "",
                    "customClass": "",
                    "suffix": "",
                    "multiple": false,
                    "defaultValue": null,
                    "protected": false,
                    "unique": false,
                    "persistent": true,
                    "hidden": false,
                    "clearOnHide": true,
                    "refreshOn": "",
                    "redrawOn": "",
                    "modalEdit": false,
                    "labelPosition": "top",
                    "description": "",
                    "errorLabel": "",
                    "tooltip": "",
                    "hideLabel": false,
                    "tabindex": "",
                    "disabled": false,
                    "autofocus": false,
                    "dbIndex": false,
                    "customDefaultValue": "",
                    "calculateValue": "",
                    "attributes": {},
                    "validateOn": "change",
                    "conditional": {
                      "show": null,
                      "when": null,
                      "eq": ""
                    },
                    "overlay": {
                      "style": "",
                      "left": "",
                      "top": "",
                      "width": "",
                      "height": ""
                    },
                    "allowCalculateOverride": false,
                    "encrypted": false,
                    "showCharCount": false,
                    "showWordCount": false,
                    "properties": {},
                    "allowMultipleMasks": false,
                    "clearOnRefresh": false,
                    "limit": 100,
                    "valueProperty": "",
                    "lazyLoad": true,
                    "filter": "",
                    "searchEnabled": true,
                    "searchField": "",
                    "minSearch": 0,
                    "readOnlyValue": false,
                    "authenticate": false,
                    "selectFields": "",
                    "searchThreshold": 0.3,
                    "fuseOptions": {
                      "include": "score",
                      "threshold": 0.3
                    },
                    "customOptions": {},
                    "id": "ecpxzx4"
                  }
                ],
                "offset": 0,
                "push": 0,
                "pull": 0,
                "width": 4
              },
              {
                "components": [
                  {
                    "label": "Community Pharmacy/club",
                    "widget": "choicesjs",
                    "tableView": true,
                    "dataSrc": "url",
                    "data": {
                      "url": "http://lamisplus.org/base-module/api/organisations",
                      "headers": [
                        {
                          "key": "",
                          "value": ""
                        }
                      ],
                      "values": [],
                      "json": "",
                      "resource": "",
                      "custom": ""
                    },
                    "template": "<span>{{ item.name }}</span>",
                    "selectThreshold": 0.3,
                    "validate": {
                      "unique": false,
                      "multiple": false,
                      "required": false,
                      "custom": "",
                      "customPrivate": false,
                      "strictDateValidation": false
                    },
                    "key": "communityPharmacyClub",
                    "type": "select",
                    "indexeddb": {
                      "filter": {}
                    },
                    "input": true,
                    "disableLimit": false,
                    "hideOnChildrenHidden": false,
                    "placeholder": "",
                    "prefix": "",
                    "customClass": "",
                    "suffix": "",
                    "multiple": false,
                    "defaultValue": null,
                    "protected": false,
                    "unique": false,
                    "persistent": true,
                    "hidden": false,
                    "clearOnHide": true,
                    "refreshOn": "",
                    "redrawOn": "",
                    "modalEdit": false,
                    "labelPosition": "top",
                    "description": "",
                    "errorLabel": "",
                    "tooltip": "",
                    "hideLabel": false,
                    "tabindex": "",
                    "disabled": false,
                    "autofocus": false,
                    "dbIndex": false,
                    "customDefaultValue": "",
                    "calculateValue": "",
                    "attributes": {},
                    "validateOn": "change",
                    "conditional": {
                      "show": null,
                      "when": null,
                      "eq": ""
                    },
                    "overlay": {
                      "style": "",
                      "left": "",
                      "top": "",
                      "width": "",
                      "height": ""
                    },
                    "allowCalculateOverride": false,
                    "encrypted": false,
                    "showCharCount": false,
                    "showWordCount": false,
                    "properties": {},
                    "allowMultipleMasks": false,
                    "clearOnRefresh": false,
                    "limit": 100,
                    "valueProperty": "",
                    "lazyLoad": true,
                    "filter": "",
                    "searchEnabled": true,
                    "searchField": "",
                    "minSearch": 0,
                    "readOnlyValue": false,
                    "authenticate": false,
                    "selectFields": "",
                    "searchThreshold": 0.3,
                    "fuseOptions": {
                      "include": "score",
                      "threshold": 0.3
                    },
                    "customOptions": {},
                    "id": "eg3m44g"
                  }
                ],
                "offset": 0,
                "push": 0,
                "pull": 0,
                "width": 4
              }
            ],
            "tableView": false,
            "key": "columns2",
            "type": "columns",
            "input": false,
            "path": "columns2",
            "placeholder": "",
            "prefix": "",
            "customClass": "",
            "suffix": "",
            "multiple": false,
            "defaultValue": null,
            "protected": false,
            "unique": false,
            "persistent": false,
            "hidden": false,
            "clearOnHide": false,
            "refreshOn": "",
            "redrawOn": "",
            "modalEdit": false,
            "labelPosition": "top",
            "description": "",
            "errorLabel": "",
            "tooltip": "",
            "hideLabel": false,
            "tabindex": "",
            "disabled": false,
            "autofocus": false,
            "dbIndex": false,
            "customDefaultValue": "",
            "calculateValue": "",
            "widget": null,
            "attributes": {},
            "validateOn": "change",
            "validate": {
              "required": false,
              "custom": "",
              "customPrivate": false,
              "strictDateValidation": false
            },
            "conditional": {
              "show": null,
              "when": null,
              "eq": ""
            },
            "overlay": {
              "style": "",
              "left": "",
              "top": "",
              "width": "",
              "height": ""
            },
            "allowCalculateOverride": false,
            "encrypted": false,
            "showCharCount": false,
            "showWordCount": false,
            "properties": {},
            "allowMultipleMasks": false,
            "tree": false,
            "autoAdjust": false,
            "hideOnChildrenHidden": false,
            "id": "eou74sh"
          },
          {
            "label": "Columns",
            "columns": [
              {
                "components": [
                  {
                    "label": "Address",
                    "autoExpand": false,
                    "spellcheck": true,
                    "tableView": true,
                    "validate": {
                      "unique": false,
                      "multiple": false,
                      "required": false,
                      "custom": "",
                      "customPrivate": false,
                      "strictDateValidation": false,
                      "minLength": "",
                      "maxLength": "",
                      "pattern": "",
                      "minWords": "",
                      "maxWords": ""
                    },
                    "key": "address",
                    "type": "textarea",
                    "input": true,
                    "hideOnChildrenHidden": false,
                    "placeholder": "",
                    "prefix": "",
                    "customClass": "",
                    "suffix": "",
                    "multiple": false,
                    "defaultValue": null,
                    "protected": false,
                    "unique": false,
                    "persistent": true,
                    "hidden": false,
                    "clearOnHide": true,
                    "refreshOn": "",
                    "redrawOn": "",
                    "modalEdit": false,
                    "labelPosition": "top",
                    "description": "",
                    "errorLabel": "",
                    "tooltip": "",
                    "hideLabel": false,
                    "tabindex": "",
                    "disabled": false,
                    "autofocus": false,
                    "dbIndex": false,
                    "customDefaultValue": "",
                    "calculateValue": "",
                    "widget": {
                      "type": "input"
                    },
                    "attributes": {},
                    "validateOn": "change",
                    "conditional": {
                      "show": null,
                      "when": null,
                      "eq": ""
                    },
                    "overlay": {
                      "style": "",
                      "left": "",
                      "top": "",
                      "width": "",
                      "height": ""
                    },
                    "allowCalculateOverride": false,
                    "encrypted": false,
                    "showCharCount": false,
                    "showWordCount": false,
                    "properties": {},
                    "allowMultipleMasks": false,
                    "mask": false,
                    "inputType": "text",
                    "inputFormat": "html",
                    "inputMask": "",
                    "rows": 3,
                    "wysiwyg": false,
                    "editor": "",
                    "id": "ejn5emg"
                  }
                ],
                "offset": 0,
                "push": 0,
                "pull": 0,
                "width": 4
              },
              {
                "components": [
                  {
                    "label": "Phone Number",
                    "inputMask": "(999) 999-999-99",
                    "spellcheck": true,
                    "tableView": true,
                    "validate": {
                      "unique": false,
                      "multiple": false,
                      "required": false,
                      "custom": "",
                      "customPrivate": false,
                      "strictDateValidation": false,
                      "minLength": "",
                      "maxLength": "",
                      "pattern": ""
                    },
                    "key": "phone_no",
                    "type": "phoneNumber",
                    "input": true,
                    "hideOnChildrenHidden": false,
                    "placeholder": "",
                    "prefix": "",
                    "customClass": "",
                    "suffix": "",
                    "multiple": false,
                    "defaultValue": null,
                    "protected": false,
                    "unique": false,
                    "persistent": true,
                    "hidden": false,
                    "clearOnHide": true,
                    "refreshOn": "",
                    "redrawOn": "",
                    "modalEdit": false,
                    "labelPosition": "top",
                    "description": "",
                    "errorLabel": "",
                    "tooltip": "",
                    "hideLabel": false,
                    "tabindex": "",
                    "disabled": false,
                    "autofocus": false,
                    "dbIndex": false,
                    "customDefaultValue": "",
                    "calculateValue": "",
                    "widget": {
                      "type": "input"
                    },
                    "attributes": {},
                    "validateOn": "change",
                    "conditional": {
                      "show": null,
                      "when": null,
                      "eq": ""
                    },
                    "overlay": {
                      "style": "",
                      "left": "",
                      "top": "",
                      "width": "",
                      "height": ""
                    },
                    "allowCalculateOverride": false,
                    "encrypted": false,
                    "showCharCount": false,
                    "showWordCount": false,
                    "properties": {},
                    "allowMultipleMasks": false,
                    "mask": false,
                    "inputType": "tel",
                    "inputFormat": "plain",
                    "id": "eh4gqw"
                  }
                ],
                "offset": 0,
                "push": 0,
                "pull": 0,
                "width": 4
              }
            ],
            "tableView": false,
            "key": "columns3",
            "type": "columns",
            "input": false,
            "path": "columns3",
            "placeholder": "",
            "prefix": "",
            "customClass": "",
            "suffix": "",
            "multiple": false,
            "defaultValue": null,
            "protected": false,
            "unique": false,
            "persistent": false,
            "hidden": false,
            "clearOnHide": false,
            "refreshOn": "",
            "redrawOn": "",
            "modalEdit": false,
            "labelPosition": "top",
            "description": "",
            "errorLabel": "",
            "tooltip": "",
            "hideLabel": false,
            "tabindex": "",
            "disabled": false,
            "autofocus": false,
            "dbIndex": false,
            "customDefaultValue": "",
            "calculateValue": "",
            "widget": null,
            "attributes": {},
            "validateOn": "change",
            "validate": {
              "required": false,
              "custom": "",
              "customPrivate": false,
              "strictDateValidation": false
            },
            "conditional": {
              "show": null,
              "when": null,
              "eq": ""
            },
            "overlay": {
              "style": "",
              "left": "",
              "top": "",
              "width": "",
              "height": ""
            },
            "allowCalculateOverride": false,
            "encrypted": false,
            "showCharCount": false,
            "showWordCount": false,
            "properties": {},
            "allowMultipleMasks": false,
            "tree": false,
            "autoAdjust": false,
            "hideOnChildrenHidden": false,
            "id": "exwh80n"
          }
        ],
        "path": "community_pharmacy",
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "hideLabel": false,
        "tabindex": "",
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "e9b1dok"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Viral Load Assessment done",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "url",
                "data": {
                  "resource": "",
                  "json": "",
                  "url": "http://lamisplus.org/base-module/api/application-codesets/codesetGroup?codesetGroup=VIRAL%20LOAD%20ASSESSMENT%20DONE",
                  "custom": "",
                  "headers": [
                    {
                      "key": "",
                      "value": ""
                    }
                  ],
                  "values": []
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.display }}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "viral_load_assessment",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "ek5rveh",
                "defaultValue": "",
                "selectValues": "",
                "disableLimit": false,
                "sort": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "CD4 Count Assessment Done",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "url",
                "data": {
                  "resource": "",
                  "json": "",
                  "url": "http://lamisplus.org/base-module/api/application-codesets/codesetGroup?codesetGroup=CD4%20COUNT%20ASSESSMENT%20DONE",
                  "custom": "",
                  "headers": [
                    {
                      "key": "",
                      "value": ""
                    }
                  ],
                  "values": []
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{ item.display}}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "cd4_assessed",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "eleh6wq",
                "defaultValue": "",
                "selectValues": "",
                "disableLimit": false,
                "sort": "",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Current Viral Load",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": false,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "delimiter": false,
                "requireDecimal": false,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "min": "",
                  "max": "",
                  "unique": false,
                  "multiple": false,
                  "strictDateValidation": false,
                  "step": "any",
                  "integer": ""
                },
                "errorLabel": "",
                "key": "last_viral_load",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "number",
                "input": true,
                "hideOnChildrenHidden": false,
                "unique": false,
                "refreshOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "id": "ezr1xhjk",
                "defaultValue": null
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns4",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "etwfjc",
        "path": "columns4"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Date of Viral Load",
                "labelPosition": "top",
                "displayInTimezone": "viewer",
                "useLocaleSettings": true,
                "allowInput": false,
                "format": "yyyy-MM-dd",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": false,
                "modalEdit": false,
                "enableDate": true,
                "datePicker": {
                  "minDate": null,
                  "maxDate": null,
                  "disable": "",
                  "disableFunction": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "showWeeks": true,
                  "startingDay": 0,
                  "initDate": "",
                  "minMode": "day",
                  "maxMode": "year",
                  "yearRows": 4,
                  "yearColumns": 5
                },
                "enableTime": true,
                "timePicker": {
                  "showMeridian": true,
                  "hourStep": 1,
                  "minuteStep": 1,
                  "readonlyInput": false,
                  "mousewheel": true,
                  "arrowkeys": true
                },
                "multiple": false,
                "defaultValue": "",
                "defaultDate": "",
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validate": {
                  "required": true,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "validateOn": "change",
                "errorLabel": "",
                "key": "date_last_viral_load",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "datetime",
                "input": true,
                "prefix": "",
                "suffix": "<i ref=\"icon\" class=\"fa fa-calendar\" style=\"\"></i>",
                "refreshOn": "",
                "widget": {
                  "type": "calendar",
                  "displayInTimezone": "viewer",
                  "language": "en",
                  "useLocaleSettings": true,
                  "allowInput": false,
                  "mode": "single",
                  "enableTime": true,
                  "noCalendar": false,
                  "format": "yyyy-MM-dd",
                  "hourIncrement": 1,
                  "minuteIncrement": 1,
                  "time_24hr": false,
                  "minDate": null,
                  "disabledDates": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "disableFunction": "",
                  "maxDate": null
                },
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "timezone": "",
                "datepickerMode": "day",
                "id": "eobpotr",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Current CD4",
                "labelPosition": "top",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "prefix": "",
                "suffix": "",
                "widget": {
                  "type": "input"
                },
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "mask": false,
                "autofocus": false,
                "spellcheck": true,
                "disabled": false,
                "tableView": false,
                "modalEdit": false,
                "multiple": false,
                "persistent": true,
                "delimiter": false,
                "requireDecimal": false,
                "inputFormat": "plain",
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "min": "",
                  "max": "",
                  "unique": false,
                  "multiple": false,
                  "strictDateValidation": false,
                  "step": "any",
                  "integer": ""
                },
                "errorLabel": "",
                "key": "last_cd4",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "number",
                "input": true,
                "hideOnChildrenHidden": false,
                "unique": false,
                "refreshOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "id": "eeaxuql",
                "defaultValue": null
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Date of CD4",
                "labelPosition": "top",
                "displayInTimezone": "viewer",
                "useLocaleSettings": true,
                "allowInput": false,
                "format": "yyyy-MM-dd",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": false,
                "modalEdit": false,
                "enableDate": true,
                "datePicker": {
                  "minDate": null,
                  "maxDate": null,
                  "disable": "",
                  "disableFunction": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "showWeeks": true,
                  "startingDay": 0,
                  "initDate": "",
                  "minMode": "day",
                  "maxMode": "year",
                  "yearRows": 4,
                  "yearColumns": 5
                },
                "enableTime": true,
                "timePicker": {
                  "showMeridian": true,
                  "hourStep": 1,
                  "minuteStep": 1,
                  "readonlyInput": false,
                  "mousewheel": true,
                  "arrowkeys": true
                },
                "multiple": false,
                "defaultValue": "",
                "defaultDate": "",
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "validateOn": "change",
                "errorLabel": "",
                "key": "date_last_cd4",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "datetime",
                "input": true,
                "prefix": "",
                "suffix": "<i ref=\"icon\" class=\"fa fa-calendar\" style=\"\"></i>",
                "refreshOn": "",
                "widget": {
                  "type": "calendar",
                  "displayInTimezone": "viewer",
                  "language": "en",
                  "useLocaleSettings": true,
                  "allowInput": false,
                  "mode": "single",
                  "enableTime": true,
                  "noCalendar": false,
                  "format": "yyyy-MM-dd",
                  "hourIncrement": 1,
                  "minuteIncrement": 1,
                  "time_24hr": false,
                  "minDate": null,
                  "disabledDates": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "disableFunction": "",
                  "maxDate": null
                },
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "timezone": "",
                "datepickerMode": "day",
                "id": "e3d554",
                "hideOnChildrenHidden": false
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "e9r5ql6",
        "path": "columns"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Current Clinical Stage",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "url",
                "data": {
                  "resource": "",
                  "json": "",
                  "url": "http://lamisplus.org/base-module/api/application-codesets/codesetGroup?codesetGroup=CLINICAL%20STAGE",
                  "custom": "",
                  "headers": [
                    {
                      "key": "",
                      "value": ""
                    }
                  ],
                  "values": []
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{item.display}}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "unique": false,
                  "multiple": false,
                  "strictDateValidation": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "last_clinic_stage",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "hideOnChildrenHidden": false,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "e740wv",
                "defaultValue": "",
                "selectValues": "",
                "disableLimit": false,
                "sort": ""
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Date of Clinical Stage",
                "labelPosition": "top",
                "displayInTimezone": "viewer",
                "useLocaleSettings": true,
                "allowInput": false,
                "format": "yyyy-MM-dd",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": false,
                "modalEdit": false,
                "enableDate": true,
                "datePicker": {
                  "minDate": null,
                  "maxDate": null,
                  "disable": "",
                  "disableFunction": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "showWeeks": true,
                  "startingDay": 0,
                  "initDate": "",
                  "minMode": "day",
                  "maxMode": "year",
                  "yearRows": 4,
                  "yearColumns": 5
                },
                "enableTime": true,
                "timePicker": {
                  "showMeridian": true,
                  "hourStep": 1,
                  "minuteStep": 1,
                  "readonlyInput": false,
                  "mousewheel": true,
                  "arrowkeys": true
                },
                "multiple": false,
                "defaultValue": "",
                "defaultDate": "",
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "unique": false,
                  "multiple": false,
                  "strictDateValidation": false
                },
                "unique": false,
                "validateOn": "change",
                "errorLabel": "",
                "key": "date_last_clinic_stage",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "datetime",
                "input": true,
                "suffix": "<i ref=\"icon\" class=\"fa fa-calendar\" style=\"\"></i>",
                "widget": {
                  "type": "calendar",
                  "displayInTimezone": "viewer",
                  "language": "en",
                  "useLocaleSettings": true,
                  "allowInput": false,
                  "mode": "single",
                  "enableTime": true,
                  "noCalendar": false,
                  "format": "yyyy-MM-dd",
                  "hourIncrement": 1,
                  "minuteIncrement": 1,
                  "time_24hr": false,
                  "minDate": null,
                  "disabledDates": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "disableFunction": "",
                  "maxDate": null
                },
                "hideOnChildrenHidden": false,
                "prefix": "",
                "refreshOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "timezone": "",
                "datepickerMode": "day",
                "id": "eahivw8"
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "ARV Regimen",
                "labelPosition": "top",
                "widget": "choicesjs",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": true,
                "modalEdit": false,
                "multiple": false,
                "dataSrc": "url",
                "data": {
                  "resource": "",
                  "json": "",
                  "url": "http://lamisplus.org/base-module/api/regimens",
                  "custom": "",
                  "headers": [
                    {
                      "key": "",
                      "value": ""
                    }
                  ],
                  "values": []
                },
                "valueProperty": "",
                "dataType": "",
                "template": "<span>{{item.name}}</span>",
                "searchEnabled": true,
                "selectThreshold": 0.3,
                "readOnlyValue": false,
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validateOn": "change",
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "unique": false,
                  "multiple": false,
                  "strictDateValidation": false
                },
                "unique": false,
                "errorLabel": "",
                "key": "regimen",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "select",
                "indexeddb": {
                  "filter": {}
                },
                "minSearch": 0,
                "limit": 100,
                "input": true,
                "hideOnChildrenHidden": false,
                "prefix": "",
                "suffix": "",
                "refreshOn": "",
                "redrawOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "clearOnRefresh": false,
                "lazyLoad": true,
                "filter": "",
                "searchField": "",
                "authenticate": false,
                "selectFields": "",
                "searchThreshold": 0.3,
                "fuseOptions": {
                  "include": "score",
                  "threshold": 0.3
                },
                "id": "eblwrfn",
                "defaultValue": "",
                "selectValues": "",
                "disableLimit": false,
                "sort": ""
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns1",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "ejmf2nw",
        "path": "columns1"
      },
      {
        "label": "Columns",
        "columns": [
          {
            "components": [
              {
                "label": "Date of next Clinic/Lab re-eveluation",
                "labelPosition": "top",
                "displayInTimezone": "viewer",
                "useLocaleSettings": true,
                "allowInput": false,
                "format": "yyyy-MM-dd",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": false,
                "modalEdit": false,
                "enableDate": true,
                "datePicker": {
                  "minDate": null,
                  "maxDate": null,
                  "disable": "",
                  "disableFunction": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "showWeeks": true,
                  "startingDay": 0,
                  "initDate": "",
                  "minMode": "day",
                  "maxMode": "year",
                  "yearRows": 4,
                  "yearColumns": 5
                },
                "enableTime": true,
                "timePicker": {
                  "showMeridian": true,
                  "hourStep": 1,
                  "minuteStep": 1,
                  "readonlyInput": false,
                  "mousewheel": true,
                  "arrowkeys": true
                },
                "multiple": false,
                "defaultValue": "",
                "defaultDate": "",
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "unique": false,
                  "multiple": false,
                  "strictDateValidation": false
                },
                "unique": false,
                "validateOn": "change",
                "errorLabel": "",
                "key": "date_next_clinic",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "datetime",
                "input": true,
                "suffix": "<i ref=\"icon\" class=\"fa fa-calendar\" style=\"\"></i>",
                "widget": {
                  "type": "calendar",
                  "displayInTimezone": "viewer",
                  "language": "en",
                  "useLocaleSettings": true,
                  "allowInput": false,
                  "mode": "single",
                  "enableTime": true,
                  "noCalendar": false,
                  "format": "yyyy-MM-dd",
                  "hourIncrement": 1,
                  "minuteIncrement": 1,
                  "time_24hr": false,
                  "minDate": null,
                  "disabledDates": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "disableFunction": "",
                  "maxDate": null
                },
                "hideOnChildrenHidden": false,
                "prefix": "",
                "refreshOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "timezone": "",
                "datepickerMode": "day",
                "id": "ewwhdus"
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [
              {
                "label": "Date of Next ARV Refill",
                "labelPosition": "top",
                "displayInTimezone": "viewer",
                "useLocaleSettings": true,
                "allowInput": false,
                "format": "yyyy-MM-dd",
                "placeholder": "",
                "description": "",
                "tooltip": "",
                "customClass": "",
                "tabindex": "",
                "hidden": false,
                "hideLabel": false,
                "autofocus": false,
                "disabled": false,
                "tableView": false,
                "modalEdit": false,
                "enableDate": true,
                "datePicker": {
                  "minDate": null,
                  "maxDate": null,
                  "disable": "",
                  "disableFunction": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "showWeeks": true,
                  "startingDay": 0,
                  "initDate": "",
                  "minMode": "day",
                  "maxMode": "year",
                  "yearRows": 4,
                  "yearColumns": 5
                },
                "enableTime": true,
                "timePicker": {
                  "showMeridian": true,
                  "hourStep": 1,
                  "minuteStep": 1,
                  "readonlyInput": false,
                  "mousewheel": true,
                  "arrowkeys": true
                },
                "multiple": false,
                "defaultValue": "",
                "defaultDate": "",
                "customOptions": {},
                "persistent": true,
                "protected": false,
                "dbIndex": false,
                "encrypted": false,
                "redrawOn": "",
                "clearOnHide": true,
                "customDefaultValue": "",
                "calculateValue": "",
                "allowCalculateOverride": false,
                "validate": {
                  "required": false,
                  "customMessage": "",
                  "custom": "",
                  "customPrivate": false,
                  "json": "",
                  "strictDateValidation": false,
                  "unique": false,
                  "multiple": false
                },
                "unique": false,
                "validateOn": "change",
                "errorLabel": "",
                "key": "date_next_refill",
                "tags": [],
                "properties": {},
                "conditional": {
                  "show": null,
                  "when": null,
                  "eq": "",
                  "json": ""
                },
                "customConditional": "",
                "logic": [],
                "attributes": {},
                "overlay": {
                  "style": "",
                  "page": "",
                  "left": "",
                  "top": "",
                  "width": "",
                  "height": ""
                },
                "type": "datetime",
                "input": true,
                "suffix": "<i ref=\"icon\" class=\"fa fa-calendar\" style=\"\"></i>",
                "widget": {
                  "type": "calendar",
                  "displayInTimezone": "viewer",
                  "language": "en",
                  "useLocaleSettings": true,
                  "allowInput": false,
                  "mode": "single",
                  "enableTime": true,
                  "noCalendar": false,
                  "format": "yyyy-MM-dd",
                  "hourIncrement": 1,
                  "minuteIncrement": 1,
                  "time_24hr": false,
                  "minDate": null,
                  "disabledDates": "",
                  "disableWeekends": false,
                  "disableWeekdays": false,
                  "disableFunction": "",
                  "maxDate": null
                },
                "hideOnChildrenHidden": false,
                "prefix": "",
                "refreshOn": "",
                "showCharCount": false,
                "showWordCount": false,
                "allowMultipleMasks": false,
                "timezone": "",
                "datepickerMode": "day",
                "id": "er410m"
              }
            ],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          },
          {
            "components": [],
            "offset": 0,
            "push": 0,
            "pull": 0,
            "width": 4
          }
        ],
        "autoAdjust": false,
        "hideOnChildrenHidden": false,
        "customClass": "",
        "hidden": false,
        "hideLabel": false,
        "tableView": false,
        "modalEdit": false,
        "key": "columns6",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "columns",
        "input": false,
        "placeholder": "",
        "prefix": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "clearOnHide": false,
        "refreshOn": "",
        "redrawOn": "",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": null,
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "tree": false,
        "id": "eoufk1",
        "path": "columns6"
      },
      {
        "type": "button",
        "label": "Submit",
        "key": "submit",
        "size": "md",
        "block": false,
        "action": "submit",
        "disableOnInvalid": true,
        "theme": "primary",
        "input": true,
        "placeholder": "",
        "prefix": "",
        "customClass": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "hidden": false,
        "clearOnHide": true,
        "refreshOn": "",
        "redrawOn": "",
        "tableView": false,
        "modalEdit": false,
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "hideLabel": false,
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": {
          "type": "input"
        },
        "attributes": {},
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false,
          "unique": false,
          "multiple": false
        },
        "conditional": {
          "show": null,
          "when": null,
          "eq": ""
        },
        "overlay": {
          "style": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "properties": {},
        "allowMultipleMasks": false,
        "leftIcon": "",
        "rightIcon": "",
        "dataGridLabel": true,
        "id": "epwb88e"
      }
    ]
  }