export const data = {
  "display": "",
  "components": [
    {
      "label": "ENHANCED ADHERENCE COUNSELLING",
      "tag": "p",
      "className": "",
      "attrs": [
        {
          "attr": "",
          "value": ""
        }
      ],
      "content": "<span style=\"color:#B87108\">ENHANCED ADHERENCE COUNSELLING</span>\n<hr>",
      "refreshOnChange": false,
      "customClass": "",
      "hidden": false,
      "tableView": false,
      "modalEdit": false,
      "key": "enhancedAdherenceCounselling",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "htmlelement",
      "input": false,
      "validate": {
        "unique": false,
        "multiple": false,
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false
      },
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": true,
      "refreshOn": "",
      "redrawOn": "",
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "hideLabel": false,
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "widget": null,
      "validateOn": "change",
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "id": "e6m468c"
    },
    {
      "label": "Columns",
      "columns": [
        {
          "components": [
            {
              "label": "Date of 1st EAC Session",
              "labelPosition": "top",
              "displayInTimezone": "viewer",
              "useLocaleSettings": true,
              "allowInput": false,
              "format": "yyyy-MM-dd",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "autofocus": false,
              "disabled": false,
              "tableView": false,
              "modalEdit": false,
              "enableDate": true,
              "datePicker": {
                "minDate": null,
                "maxDate": null,
                "disable": "",
                "disableFunction": "",
                "disableWeekends": false,
                "disableWeekdays": false,
                "showWeeks": true,
                "startingDay": 0,
                "initDate": "",
                "minMode": "day",
                "maxMode": "year",
                "yearRows": 4,
                "yearColumns": 5
              },
              "enableTime": true,
              "timePicker": {
                "showMeridian": true,
                "hourStep": 1,
                "minuteStep": 1,
                "readonlyInput": false,
                "mousewheel": true,
                "arrowkeys": true
              },
              "multiple": false,
              "defaultValue": "",
              "defaultDate": "var today = moment() ",
              "customOptions": {},
              "persistent": true,
              "protected": false,
              "dbIndex": false,
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validate": {
                "required": false,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "strictDateValidation": false,
                "unique": false,
                "multiple": false
              },
              "unique": false,
              "validateOn": "change",
              "errorLabel": "",
              "key": "date_eac1",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "datetime",
              "input": true,
              "prefix": "",
              "suffix": "<i ref=\"icon\" class=\"fa fa-calendar\" style=\"\"></i>",
              "refreshOn": "",
              "widget": {
                "type": "calendar",
                "displayInTimezone": "viewer",
                "language": "en",
                "useLocaleSettings": true,
                "allowInput": false,
                "mode": "single",
                "enableTime": true,
                "noCalendar": false,
                "format": "yyyy-MM-dd",
                "hourIncrement": 1,
                "minuteIncrement": 1,
                "time_24hr": false,
                "minDate": null,
                "disabledDates": "",
                "disableWeekends": false,
                "disableWeekdays": false,
                "disableFunction": "",
                "maxDate": null
              },
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "timezone": "",
              "datepickerMode": "day",
              "id": "elxhxxh",
              "hideOnChildrenHidden": false
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0
        },
        {
          "components": [
            {
              "label": "Date of 2nd EAC Session",
              "labelPosition": "top",
              "displayInTimezone": "viewer",
              "useLocaleSettings": true,
              "allowInput": false,
              "format": "yyyy-MM-dd",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "autofocus": false,
              "disabled": false,
              "tableView": false,
              "modalEdit": false,
              "enableDate": true,
              "datePicker": {
                "minDate": null,
                "maxDate": null,
                "disable": "",
                "disableFunction": "",
                "disableWeekends": false,
                "disableWeekdays": false,
                "showWeeks": true,
                "startingDay": 0,
                "initDate": "",
                "minMode": "day",
                "maxMode": "year",
                "yearRows": 4,
                "yearColumns": 5
              },
              "enableTime": true,
              "timePicker": {
                "showMeridian": true,
                "hourStep": 1,
                "minuteStep": 1,
                "readonlyInput": false,
                "mousewheel": true,
                "arrowkeys": true
              },
              "multiple": false,
              "defaultValue": "",
              "defaultDate": "",
              "customOptions": {},
              "persistent": true,
              "protected": false,
              "dbIndex": false,
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validate": {
                "required": false,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "strictDateValidation": false,
                "unique": false,
                "multiple": false
              },
              "unique": false,
              "validateOn": "change",
              "errorLabel": "",
              "key": "date_eac2",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "datetime",
              "input": true,
              "prefix": "",
              "suffix": "<i ref=\"icon\" class=\"fa fa-calendar\" style=\"\"></i>",
              "refreshOn": "",
              "widget": {
                "type": "calendar",
                "displayInTimezone": "viewer",
                "language": "en",
                "useLocaleSettings": true,
                "allowInput": false,
                "mode": "single",
                "enableTime": true,
                "noCalendar": false,
                "format": "yyyy-MM-dd",
                "hourIncrement": 1,
                "minuteIncrement": 1,
                "time_24hr": false,
                "minDate": null,
                "disabledDates": "",
                "disableWeekends": false,
                "disableWeekdays": false,
                "disableFunction": "",
                "maxDate": null
              },
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "timezone": "",
              "datepickerMode": "day",
              "id": "e1ku8if",
              "hideOnChildrenHidden": false
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0
        }
      ],
      "autoAdjust": false,
      "hideOnChildrenHidden": false,
      "customClass": "",
      "hidden": false,
      "hideLabel": false,
      "tableView": false,
      "modalEdit": false,
      "key": "columns",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "columns",
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": false,
      "refreshOn": "",
      "redrawOn": "",
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "tree": false,
      "id": "eo32hxq",
      "path": "columns"
    },
    {
      "label": "Columns",
      "columns": [
        {
          "components": [
            {
              "label": "Date of 3rd EAC Session",
              "labelPosition": "top",
              "displayInTimezone": "viewer",
              "useLocaleSettings": true,
              "allowInput": false,
              "format": "yyyy-MM-dd",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "autofocus": false,
              "disabled": false,
              "tableView": false,
              "modalEdit": false,
              "enableDate": true,
              "datePicker": {
                "minDate": null,
                "maxDate": null,
                "disable": "",
                "disableFunction": "",
                "disableWeekends": false,
                "disableWeekdays": false,
                "showWeeks": true,
                "startingDay": 0,
                "initDate": "",
                "minMode": "day",
                "maxMode": "year",
                "yearRows": 4,
                "yearColumns": 5
              },
              "enableTime": true,
              "timePicker": {
                "showMeridian": true,
                "hourStep": 1,
                "minuteStep": 1,
                "readonlyInput": false,
                "mousewheel": true,
                "arrowkeys": true
              },
              "multiple": false,
              "defaultValue": "",
              "defaultDate": "",
              "customOptions": {},
              "persistent": true,
              "protected": false,
              "dbIndex": false,
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validate": {
                "required": false,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "strictDateValidation": false,
                "unique": false,
                "multiple": false
              },
              "unique": false,
              "validateOn": "change",
              "errorLabel": "",
              "key": "date_eac3",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "datetime",
              "input": true,
              "prefix": "",
              "suffix": "<i ref=\"icon\" class=\"fa fa-calendar\" style=\"\"></i>",
              "refreshOn": "",
              "widget": {
                "type": "calendar",
                "displayInTimezone": "viewer",
                "language": "en",
                "useLocaleSettings": true,
                "allowInput": false,
                "mode": "single",
                "enableTime": true,
                "noCalendar": false,
                "format": "yyyy-MM-dd",
                "hourIncrement": 1,
                "minuteIncrement": 1,
                "time_24hr": false,
                "minDate": null,
                "disabledDates": "",
                "disableWeekends": false,
                "disableWeekdays": false,
                "disableFunction": "",
                "maxDate": null
              },
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "timezone": "",
              "datepickerMode": "day",
              "id": "eh81qau",
              "hideOnChildrenHidden": false
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0
        },
        {
          "components": [
            {
              "label": "Date of Repeat VL Sample Collection",
              "labelPosition": "top",
              "displayInTimezone": "viewer",
              "useLocaleSettings": true,
              "allowInput": false,
              "format": "yyyy-MM-dd",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "autofocus": false,
              "disabled": false,
              "tableView": false,
              "modalEdit": false,
              "enableDate": true,
              "datePicker": {
                "minDate": null,
                "maxDate": null,
                "disable": "",
                "disableFunction": "",
                "disableWeekends": false,
                "disableWeekdays": false,
                "showWeeks": true,
                "startingDay": 0,
                "initDate": "",
                "minMode": "day",
                "maxMode": "year",
                "yearRows": 4,
                "yearColumns": 5
              },
              "enableTime": true,
              "timePicker": {
                "showMeridian": true,
                "hourStep": 1,
                "minuteStep": 1,
                "readonlyInput": false,
                "mousewheel": true,
                "arrowkeys": true
              },
              "multiple": false,
              "defaultValue": "",
              "defaultDate": "",
              "customOptions": {},
              "persistent": true,
              "protected": false,
              "dbIndex": false,
              "encrypted": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validate": {
                "required": false,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "strictDateValidation": false,
                "unique": false,
                "multiple": false
              },
              "unique": false,
              "validateOn": "change",
              "errorLabel": "",
              "key": "date_sample_collected",
              "tags": [],
              "properties": {},
              "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
              },
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "type": "datetime",
              "input": true,
              "prefix": "",
              "suffix": "<i ref=\"icon\" class=\"fa fa-calendar\" style=\"\"></i>",
              "refreshOn": "",
              "widget": {
                "type": "calendar",
                "displayInTimezone": "viewer",
                "language": "en",
                "useLocaleSettings": true,
                "allowInput": false,
                "mode": "single",
                "enableTime": true,
                "noCalendar": false,
                "format": "yyyy-MM-dd",
                "hourIncrement": 1,
                "minuteIncrement": 1,
                "time_24hr": false,
                "minDate": null,
                "disabledDates": "",
                "disableWeekends": false,
                "disableWeekdays": false,
                "disableFunction": "",
                "maxDate": null
              },
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "timezone": "",
              "datepickerMode": "day",
              "id": "epey24r",
              "hideOnChildrenHidden": false
            }
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0
        }
      ],
      "autoAdjust": false,
      "hideOnChildrenHidden": false,
      "customClass": "",
      "hidden": false,
      "hideLabel": false,
      "tableView": false,
      "modalEdit": false,
      "key": "columns1",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "columns",
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": false,
      "refreshOn": "",
      "redrawOn": "",
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "tree": false,
      "id": "e9sedpp",
      "path": "columns1"
    },
    {
      "label": "Columns",
      "columns": [
        {
          "components": [
            {
              "label": "Clinician Notes",
              "editor": "ckeditor",
              "spellcheck": true,
              "tableView": true,
              "validate": {
                "unique": false,
                "multiple": false,
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "minLength": "",
                "maxLength": "",
                "pattern": "",
                "minWords": "",
                "maxWords": ""
              },
              "key": "notes",
              "type": "textarea",
              "input": true,
              "hideOnChildrenHidden": false,
              "placeholder": "",
              "prefix": "",
              "customClass": "",
              "suffix": "",
              "multiple": false,
              "defaultValue": null,
              "protected": false,
              "unique": false,
              "persistent": true,
              "hidden": false,
              "clearOnHide": true,
              "refreshOn": "",
              "redrawOn": "",
              "modalEdit": false,
              "labelPosition": "top",
              "description": "",
              "errorLabel": "",
              "tooltip": "",
              "hideLabel": false,
              "tabindex": "",
              "disabled": false,
              "autofocus": false,
              "dbIndex": false,
              "customDefaultValue": "",
              "calculateValue": "",
              "widget": {
                "type": "input"
              },
              "attributes": {},
              "validateOn": "change",
              "conditional": {
                "show": null,
                "when": null,
                "eq": ""
              },
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
              },
              "allowCalculateOverride": false,
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "properties": {},
              "allowMultipleMasks": false,
              "mask": false,
              "inputType": "text",
              "inputFormat": "html",
              "inputMask": "",
              "rows": 3,
              "wysiwyg": false,
              "id": "en4z1kw"
            }
          ],
          "offset": 0,
          "push": 0,
          "pull": 0,
          "width": 9
        },
        {
          "components": [],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0
        }
      ],
      "autoAdjust": false,
      "hideOnChildrenHidden": false,
      "customClass": "",
      "hidden": false,
      "hideLabel": false,
      "tableView": false,
      "modalEdit": false,
      "key": "columns2",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "columns",
      "input": false,
      "path": "columns2",
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": false,
      "refreshOn": "",
      "redrawOn": "",
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "tree": false,
      "id": "e5thtkq"
    },
    {
      "label": "Submit",
      "action": "url",
      "showValidations": false,
      "theme": "primary",
      "size": "md",
      "block": false,
      "leftIcon": "fa fa-save",
      "rightIcon": "",
      "shortcut": "",
      "description": "",
      "tooltip": "",
      "customClass": "",
      "tabindex": "",
      "disableOnInvalid": true,
      "hidden": false,
      "autofocus": false,
      "disabled": false,
      "tableView": false,
      "modalEdit": false,
      "key": "submit",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "button",
      "input": true,
      "validate": {
        "unique": false,
        "multiple": false,
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false
      },
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": true,
      "refreshOn": "",
      "redrawOn": "",
      "labelPosition": "top",
      "errorLabel": "",
      "hideLabel": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "widget": {
        "type": "input"
      },
      "validateOn": "change",
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "dataGridLabel": true,
      "id": "etpam8s",
      "url": "https://lp-base-app.herokuapp.com/api/encounter",
      "headers": [
        {
          "header": "",
          "value": ""
        }
      ]
    }
  ]
}