export const data = {
    "display": "",
    "components": [
      {
        "label": "occupation",
        "labelPosition": "top",
        "widget": "choicesjs",
        "placeholder": "",
        "description": "",
        "tooltip": "",
        "customClass": "",
        "tabindex": "",
        "hidden": false,
        "hideLabel": false,
        "autofocus": false,
        "disabled": false,
        "tableView": true,
        "modalEdit": false,
        "multiple": false,
        "dataSrc": "url",
        "data": {
          "values": [
            {}
          ],
          "resource": "",
          "url": "http://lamisplus.org/base-module/api/application-codesets/codesetGroup?codesetGroup=OCCUPATION",
          "json": "",
          "custom": "",
          "headers": [
            {
              "key": "",
              "value": ""
            }
          ]
        },
        "valueProperty": "",
        "dataType": "",
        "template": "<span>{{ item.display }}</span>",
        "searchEnabled": true,
        "selectThreshold": 0.3,
        "readOnlyValue": false,
        "customOptions": {},
        "persistent": true,
        "protected": false,
        "dbIndex": false,
        "encrypted": false,
        "clearOnHide": true,
        "customDefaultValue": "",
        "calculateValue": "",
        "allowCalculateOverride": false,
        "validateOn": "change",
        "validate": {
          "required": false,
          "customMessage": "",
          "custom": "",
          "customPrivate": false,
          "json": "",
          "unique": false,
          "multiple": false,
          "strictDateValidation": false
        },
        "unique": false,
        "errorLabel": "",
        "key": "occupation",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "select",
        "indexeddb": {
          "filter": {}
        },
        "minSearch": 0,
        "limit": 100,
        "input": true,
        "disableLimit": false,
        "prefix": "",
        "suffix": "",
        "refreshOn": "",
        "redrawOn": "",
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "clearOnRefresh": false,
        "lazyLoad": true,
        "filter": "",
        "searchField": "",
        "authenticate": false,
        "selectFields": "",
        "searchThreshold": 0.3,
        "fuseOptions": {
          "include": "score",
          "threshold": 0.3
        },
        "id": "eh1jl8",
        "defaultValue": "",
        "selectValues": "",
        "sort": ""
      },
      {
        "label": "You choose Unemployed, what are you doing with your life?",
        "labelPosition": "top",
        "placeholder": "",
        "description": "",
        "tooltip": "",
        "prefix": "",
        "suffix": "",
        "widget": {
          "type": "input"
        },
        "inputMask": "",
        "allowMultipleMasks": false,
        "customClass": "",
        "tabindex": "",
        "hidden": false,
        "hideLabel": false,
        "showWordCount": false,
        "showCharCount": false,
        "mask": false,
        "autofocus": false,
        "spellcheck": true,
        "disabled": false,
        "tableView": true,
        "modalEdit": false,
        "multiple": false,
        "persistent": true,
        "inputFormat": "plain",
        "protected": false,
        "dbIndex": false,
        "case": "",
        "encrypted": false,
        "redrawOn": "",
        "clearOnHide": true,
        "customDefaultValue": "",
        "calculateValue": "",
        "allowCalculateOverride": false,
        "validateOn": "change",
        "validate": {
          "required": false,
          "pattern": "",
          "customMessage": "",
          "custom": "",
          "customPrivate": false,
          "json": "",
          "minLength": "",
          "maxLength": "",
          "unique": false,
          "multiple": false,
          "strictDateValidation": false
        },
        "unique": false,
        "errorLabel": "",
        "key": "youChooseUnemployedWhatAreYouDoingWithYourLife",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "console.log(data.occupation.display); show = ( data.occupation && data.occupation.display === 'Unemployed' )",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "textfield",
        "input": true,
        "refreshOn": "",
        "inputType": "text",
        "id": "exw3it",
        "defaultValue": ""
      },
      {
        "label": "You choose Employed, tell us what you do?",
        "labelPosition": "top",
        "placeholder": "",
        "description": "",
        "tooltip": "",
        "prefix": "",
        "suffix": "",
        "widget": {
          "type": "input"
        },
        "inputMask": "",
        "allowMultipleMasks": false,
        "customClass": "",
        "tabindex": "",
        "hidden": true,
        "hideLabel": false,
        "showWordCount": false,
        "showCharCount": false,
        "mask": false,
        "autofocus": false,
        "spellcheck": true,
        "disabled": false,
        "tableView": true,
        "modalEdit": false,
        "multiple": false,
        "persistent": true,
        "inputFormat": "plain",
        "protected": false,
        "dbIndex": false,
        "case": "",
        "encrypted": false,
        "redrawOn": "",
        "clearOnHide": true,
        "customDefaultValue": "",
        "calculateValue": "",
        "allowCalculateOverride": false,
        "validateOn": "change",
        "validate": {
          "required": false,
          "pattern": "",
          "customMessage": "",
          "custom": "",
          "customPrivate": false,
          "json": "",
          "minLength": "",
          "maxLength": "",
          "unique": false,
          "multiple": false,
          "strictDateValidation": false
        },
        "unique": false,
        "errorLabel": "",
        "key": "youChooseEmployedWhatAreYouDoingWithYourLife",
        "tags": [],
        "properties": {},
        "conditional": {
          "show": null,
          "when": null,
          "eq": "",
          "json": ""
        },
        "customConditional": "show = ( data.occupation && data.occupation.display === 'Employed' )",
        "logic": [],
        "attributes": {},
        "overlay": {
          "style": "",
          "page": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "type": "textfield",
        "input": true,
        "refreshOn": "",
        "inputType": "text",
        "id": "elrfepo",
        "defaultValue": ""
      },
      {
        "type": "button",
        "label": "Submit",
        "key": "submit",
        "size": "md",
        "block": false,
        "action": "submit",
        "disableOnInvalid": true,
        "theme": "primary",
        "input": true,
        "placeholder": "",
        "prefix": "",
        "customClass": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": false,
        "hidden": false,
        "clearOnHide": true,
        "refreshOn": "",
        "redrawOn": "",
        "tableView": false,
        "modalEdit": false,
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "hideLabel": false,
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "widget": {
          "type": "input"
        },
        "attributes": {},
        "validateOn": "change",
        "validate": {
          "required": false,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false,
          "unique": false,
          "multiple": false
        },
        "conditional": {
          "show": null,
          "when": null,
          "eq": ""
        },
        "overlay": {
          "style": "",
          "left": "",
          "top": "",
          "width": "",
          "height": ""
        },
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "properties": {},
        "allowMultipleMasks": false,
        "leftIcon": "",
        "rightIcon": "",
        "dataGridLabel": true,
        "id": "eocns1"
      }
    ]
  };
