--
-- Data for Name: module; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.module (id, active, artifact_id, base_package, date_created, description, name, version, created_by, modified_by, archived, module_type, uuid, date_installed, installed_by, status, main, batch_no, artifact, build_time, code, data, process_config, started, uninstall, date_modified) VALUES ('3', true, NULL, NULL, NULL, NULL, 'HTS', NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL);
INSERT INTO public.module (id, active, artifact_id, base_package, date_created, description, name, version, created_by, modified_by, archived, module_type, uuid, date_installed, installed_by, status, main, batch_no, artifact, build_time, code, data, process_config, started, uninstall, date_modified) VALUES ('4', true, NULL, NULL, NULL, NULL, 'TB', NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL);
INSERT INTO public.module (id, active, artifact_id, base_package, date_created, description, name, version, created_by, modified_by, archived, module_type, uuid, date_installed, installed_by, status, main, batch_no, artifact, build_time, code, data, process_config, started, uninstall, date_modified) VALUES ('5', true, NULL, NULL, NULL, NULL, 'PMTCT', NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL);
INSERT INTO public.module (id, active, artifact_id, base_package, date_created, description, name, version, created_by, modified_by, archived, module_type, uuid, date_installed, installed_by, status, main, batch_no, artifact, build_time, code, data, process_config, started, uninstall, date_modified) VALUES ('6', true, NULL, NULL, NULL, NULL, 'KEY POP', NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL);
INSERT INTO public.module (id, active, artifact_id, base_package, date_created, description, name, version, created_by, modified_by, archived, module_type, uuid, date_installed, installed_by, status, main, batch_no, artifact, build_time, code, data, process_config, started, uninstall, date_modified) VALUES ('7', true, NULL, NULL, NULL, NULL, 'SURVEILLANCE', NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL);
INSERT INTO public.module (id, active, artifact_id, base_package, date_created, description, name, version, created_by, modified_by, archived, module_type, uuid, date_installed, installed_by, status, main, batch_no, artifact, build_time, code, data, process_config, started, uninstall, date_modified) VALUES ('2', true, NULL, NULL, NULL, NULL, 'HIV', NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL);
INSERT INTO public.module (id, active, artifact_id, base_package, date_created, description, name, version, created_by, modified_by, archived, module_type, uuid, date_installed, installed_by, status, main, batch_no, artifact, build_time, code, data, process_config, started, uninstall, date_modified) VALUES ('1', true, NULL, NULL, NULL, NULL, 'CORE', NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NULL);
