export const initialfieldState_patientRegistration = {
  hospitalNumber: '',
  firstName: '',
  lastName: '',
  email: '',
  facilityId: '1',
  dobEstimated: '',
  educationId: '',
  genderId: '',
  maritalStatusId: '',
  occupationId: '',
  alternatePhoneNumber: '',
  mobilePhoneNumber:'',
  personRelativeDTOs: [],
  address: '',
  city: '',
  countryId: '',
  landmark: '',
  provinceId: '2',
  zipCode: '',
  stateId: '',
  street: '',
  dob: '',
  dateRegistration: ''
}
